// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_remediation_step.sql

package pilotdb

import (
	"context"
)

const createRemediationStep = `-- name: CreateRemediationStep :one
INSERT INTO
    remediation_steps (
        tenant_id,
        ticket_id,
        action_name,
        sequence,
        status
    )
VALUES ($1, $2, $3, $4, 'pending')
RETURNING
    id
`

type CreateRemediationStepParams struct {
	TenantID   int32  `json:"tenant_id"`
	TicketID   int32  `json:"ticket_id"`
	ActionName string `json:"action_name"`
	Sequence   int32  `json:"sequence"`
}

func (q *Queries) CreateRemediationStep(ctx context.Context, arg CreateRemediationStepParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRemediationStep,
		arg.TenantID,
		arg.TicketID,
		arg.ActionName,
		arg.Sequence,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
