// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_ticket_tenant_id.sql

package pilotdb

import (
	"context"
)

const getTicketTenantID = `-- name: GetTicketTenantID :one
SELECT tenant_id FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketTenantID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getTicketTenantID, id)
	var tenant_id int32
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
