// Code generated by ent, DO NOT EDIT.

package timeoffpolicy

import (
	"sent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldDescription, v))
}

// AnnualAllowance applies equality check predicate on the "annual_allowance" field. It's identical to AnnualAllowanceEQ.
func AnnualAllowance(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldAnnualAllowance, v))
}

// AccrualRate applies equality check predicate on the "accrual_rate" field. It's identical to AccrualRateEQ.
func AccrualRate(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldAccrualRate, v))
}

// CarryOverMax applies equality check predicate on the "carry_over_max" field. It's identical to CarryOverMaxEQ.
func CarryOverMax(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldCarryOverMax, v))
}

// RequiresApproval applies equality check predicate on the "requires_approval" field. It's identical to RequiresApprovalEQ.
func RequiresApproval(v bool) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldRequiresApproval, v))
}

// MinNoticeDays applies equality check predicate on the "min_notice_days" field. It's identical to MinNoticeDaysEQ.
func MinNoticeDays(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldMinNoticeDays, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldContainsFold(FieldDescription, v))
}

// PolicyTypeEQ applies the EQ predicate on the "policy_type" field.
func PolicyTypeEQ(v PolicyType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldPolicyType, v))
}

// PolicyTypeNEQ applies the NEQ predicate on the "policy_type" field.
func PolicyTypeNEQ(v PolicyType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldPolicyType, v))
}

// PolicyTypeIn applies the In predicate on the "policy_type" field.
func PolicyTypeIn(vs ...PolicyType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldPolicyType, vs...))
}

// PolicyTypeNotIn applies the NotIn predicate on the "policy_type" field.
func PolicyTypeNotIn(vs ...PolicyType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldPolicyType, vs...))
}

// LeaveTypeEQ applies the EQ predicate on the "leave_type" field.
func LeaveTypeEQ(v LeaveType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldLeaveType, v))
}

// LeaveTypeNEQ applies the NEQ predicate on the "leave_type" field.
func LeaveTypeNEQ(v LeaveType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldLeaveType, v))
}

// LeaveTypeIn applies the In predicate on the "leave_type" field.
func LeaveTypeIn(vs ...LeaveType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldLeaveType, vs...))
}

// LeaveTypeNotIn applies the NotIn predicate on the "leave_type" field.
func LeaveTypeNotIn(vs ...LeaveType) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldLeaveType, vs...))
}

// AnnualAllowanceEQ applies the EQ predicate on the "annual_allowance" field.
func AnnualAllowanceEQ(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldAnnualAllowance, v))
}

// AnnualAllowanceNEQ applies the NEQ predicate on the "annual_allowance" field.
func AnnualAllowanceNEQ(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldAnnualAllowance, v))
}

// AnnualAllowanceIn applies the In predicate on the "annual_allowance" field.
func AnnualAllowanceIn(vs ...float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldAnnualAllowance, vs...))
}

// AnnualAllowanceNotIn applies the NotIn predicate on the "annual_allowance" field.
func AnnualAllowanceNotIn(vs ...float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldAnnualAllowance, vs...))
}

// AnnualAllowanceGT applies the GT predicate on the "annual_allowance" field.
func AnnualAllowanceGT(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldAnnualAllowance, v))
}

// AnnualAllowanceGTE applies the GTE predicate on the "annual_allowance" field.
func AnnualAllowanceGTE(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldAnnualAllowance, v))
}

// AnnualAllowanceLT applies the LT predicate on the "annual_allowance" field.
func AnnualAllowanceLT(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldAnnualAllowance, v))
}

// AnnualAllowanceLTE applies the LTE predicate on the "annual_allowance" field.
func AnnualAllowanceLTE(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldAnnualAllowance, v))
}

// AccrualRateEQ applies the EQ predicate on the "accrual_rate" field.
func AccrualRateEQ(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldAccrualRate, v))
}

// AccrualRateNEQ applies the NEQ predicate on the "accrual_rate" field.
func AccrualRateNEQ(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldAccrualRate, v))
}

// AccrualRateIn applies the In predicate on the "accrual_rate" field.
func AccrualRateIn(vs ...float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldAccrualRate, vs...))
}

// AccrualRateNotIn applies the NotIn predicate on the "accrual_rate" field.
func AccrualRateNotIn(vs ...float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldAccrualRate, vs...))
}

// AccrualRateGT applies the GT predicate on the "accrual_rate" field.
func AccrualRateGT(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldAccrualRate, v))
}

// AccrualRateGTE applies the GTE predicate on the "accrual_rate" field.
func AccrualRateGTE(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldAccrualRate, v))
}

// AccrualRateLT applies the LT predicate on the "accrual_rate" field.
func AccrualRateLT(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldAccrualRate, v))
}

// AccrualRateLTE applies the LTE predicate on the "accrual_rate" field.
func AccrualRateLTE(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldAccrualRate, v))
}

// AccrualRateIsNil applies the IsNil predicate on the "accrual_rate" field.
func AccrualRateIsNil() predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIsNull(FieldAccrualRate))
}

// AccrualRateNotNil applies the NotNil predicate on the "accrual_rate" field.
func AccrualRateNotNil() predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotNull(FieldAccrualRate))
}

// CarryOverMaxEQ applies the EQ predicate on the "carry_over_max" field.
func CarryOverMaxEQ(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldCarryOverMax, v))
}

// CarryOverMaxNEQ applies the NEQ predicate on the "carry_over_max" field.
func CarryOverMaxNEQ(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldCarryOverMax, v))
}

// CarryOverMaxIn applies the In predicate on the "carry_over_max" field.
func CarryOverMaxIn(vs ...float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldCarryOverMax, vs...))
}

// CarryOverMaxNotIn applies the NotIn predicate on the "carry_over_max" field.
func CarryOverMaxNotIn(vs ...float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldCarryOverMax, vs...))
}

// CarryOverMaxGT applies the GT predicate on the "carry_over_max" field.
func CarryOverMaxGT(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldCarryOverMax, v))
}

// CarryOverMaxGTE applies the GTE predicate on the "carry_over_max" field.
func CarryOverMaxGTE(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldCarryOverMax, v))
}

// CarryOverMaxLT applies the LT predicate on the "carry_over_max" field.
func CarryOverMaxLT(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldCarryOverMax, v))
}

// CarryOverMaxLTE applies the LTE predicate on the "carry_over_max" field.
func CarryOverMaxLTE(v float64) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldCarryOverMax, v))
}

// RequiresApprovalEQ applies the EQ predicate on the "requires_approval" field.
func RequiresApprovalEQ(v bool) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldRequiresApproval, v))
}

// RequiresApprovalNEQ applies the NEQ predicate on the "requires_approval" field.
func RequiresApprovalNEQ(v bool) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldRequiresApproval, v))
}

// MinNoticeDaysEQ applies the EQ predicate on the "min_notice_days" field.
func MinNoticeDaysEQ(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldMinNoticeDays, v))
}

// MinNoticeDaysNEQ applies the NEQ predicate on the "min_notice_days" field.
func MinNoticeDaysNEQ(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldMinNoticeDays, v))
}

// MinNoticeDaysIn applies the In predicate on the "min_notice_days" field.
func MinNoticeDaysIn(vs ...int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldMinNoticeDays, vs...))
}

// MinNoticeDaysNotIn applies the NotIn predicate on the "min_notice_days" field.
func MinNoticeDaysNotIn(vs ...int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldMinNoticeDays, vs...))
}

// MinNoticeDaysGT applies the GT predicate on the "min_notice_days" field.
func MinNoticeDaysGT(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldMinNoticeDays, v))
}

// MinNoticeDaysGTE applies the GTE predicate on the "min_notice_days" field.
func MinNoticeDaysGTE(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldMinNoticeDays, v))
}

// MinNoticeDaysLT applies the LT predicate on the "min_notice_days" field.
func MinNoticeDaysLT(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldMinNoticeDays, v))
}

// MinNoticeDaysLTE applies the LTE predicate on the "min_notice_days" field.
func MinNoticeDaysLTE(v int) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldMinNoticeDays, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBalances applies the HasEdge predicate on the "balances" edge.
func HasBalances() predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BalancesTable, BalancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBalancesWith applies the HasEdge predicate on the "balances" edge with a given conditions (other predicates).
func HasBalancesWith(preds ...predicate.TimeOffBalance) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(func(s *sql.Selector) {
		step := newBalancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TimeOffPolicy) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TimeOffPolicy) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TimeOffPolicy) predicate.TimeOffPolicy {
	return predicate.TimeOffPolicy(sql.NotPredicates(p))
}
