// Code generated by ent, DO NOT EDIT.

package compensationagreement

import (
	"sent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLTE(FieldID, id))
}

// BaseSalary applies equality check predicate on the "base_salary" field. It's identical to BaseSalaryEQ.
func BaseSalary(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldBaseSalary, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldCurrency, v))
}

// EffectiveDate applies equality check predicate on the "effective_date" field. It's identical to EffectiveDateEQ.
func EffectiveDate(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldEffectiveDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldCreatedAt, v))
}

// BaseSalaryEQ applies the EQ predicate on the "base_salary" field.
func BaseSalaryEQ(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldBaseSalary, v))
}

// BaseSalaryNEQ applies the NEQ predicate on the "base_salary" field.
func BaseSalaryNEQ(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNEQ(FieldBaseSalary, v))
}

// BaseSalaryIn applies the In predicate on the "base_salary" field.
func BaseSalaryIn(vs ...float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldIn(FieldBaseSalary, vs...))
}

// BaseSalaryNotIn applies the NotIn predicate on the "base_salary" field.
func BaseSalaryNotIn(vs ...float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNotIn(FieldBaseSalary, vs...))
}

// BaseSalaryGT applies the GT predicate on the "base_salary" field.
func BaseSalaryGT(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGT(FieldBaseSalary, v))
}

// BaseSalaryGTE applies the GTE predicate on the "base_salary" field.
func BaseSalaryGTE(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGTE(FieldBaseSalary, v))
}

// BaseSalaryLT applies the LT predicate on the "base_salary" field.
func BaseSalaryLT(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLT(FieldBaseSalary, v))
}

// BaseSalaryLTE applies the LTE predicate on the "base_salary" field.
func BaseSalaryLTE(v float64) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLTE(FieldBaseSalary, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldContainsFold(FieldCurrency, v))
}

// EffectiveDateEQ applies the EQ predicate on the "effective_date" field.
func EffectiveDateEQ(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldEffectiveDate, v))
}

// EffectiveDateNEQ applies the NEQ predicate on the "effective_date" field.
func EffectiveDateNEQ(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNEQ(FieldEffectiveDate, v))
}

// EffectiveDateIn applies the In predicate on the "effective_date" field.
func EffectiveDateIn(vs ...time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldIn(FieldEffectiveDate, vs...))
}

// EffectiveDateNotIn applies the NotIn predicate on the "effective_date" field.
func EffectiveDateNotIn(vs ...time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNotIn(FieldEffectiveDate, vs...))
}

// EffectiveDateGT applies the GT predicate on the "effective_date" field.
func EffectiveDateGT(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGT(FieldEffectiveDate, v))
}

// EffectiveDateGTE applies the GTE predicate on the "effective_date" field.
func EffectiveDateGTE(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGTE(FieldEffectiveDate, v))
}

// EffectiveDateLT applies the LT predicate on the "effective_date" field.
func EffectiveDateLT(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLT(FieldEffectiveDate, v))
}

// EffectiveDateLTE applies the LTE predicate on the "effective_date" field.
func EffectiveDateLTE(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLTE(FieldEffectiveDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.CompensationAgreement {
	return predicate.CompensationAgreement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.CompensationAgreement {
	return predicate.CompensationAgreement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(func(s *sql.Selector) {
		step := newEmployeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CompensationAgreement) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CompensationAgreement) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CompensationAgreement) predicate.CompensationAgreement {
	return predicate.CompensationAgreement(sql.NotPredicates(p))
}
