// Code generated by ent, DO NOT EDIT.

package timeentry

import (
	"sent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldID, id))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldEndTime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldTicketID, v))
}

// TechnicianID applies equality check predicate on the "technician_id" field. It's identical to TechnicianIDEQ.
func TechnicianID(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldTechnicianID, v))
}

// WorkType applies equality check predicate on the "work_type" field. It's identical to WorkTypeEQ.
func WorkType(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldWorkType, v))
}

// DurationHours applies equality check predicate on the "duration_hours" field. It's identical to DurationHoursEQ.
func DurationHours(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldDurationHours, v))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldInvoiceID, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotNull(FieldEndTime))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDIsNil applies the IsNil predicate on the "ticket_id" field.
func TicketIDIsNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIsNull(FieldTicketID))
}

// TicketIDNotNil applies the NotNil predicate on the "ticket_id" field.
func TicketIDNotNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotNull(FieldTicketID))
}

// TechnicianIDEQ applies the EQ predicate on the "technician_id" field.
func TechnicianIDEQ(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldTechnicianID, v))
}

// TechnicianIDNEQ applies the NEQ predicate on the "technician_id" field.
func TechnicianIDNEQ(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldTechnicianID, v))
}

// TechnicianIDIn applies the In predicate on the "technician_id" field.
func TechnicianIDIn(vs ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldTechnicianID, vs...))
}

// TechnicianIDNotIn applies the NotIn predicate on the "technician_id" field.
func TechnicianIDNotIn(vs ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldTechnicianID, vs...))
}

// TechnicianIDGT applies the GT predicate on the "technician_id" field.
func TechnicianIDGT(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldTechnicianID, v))
}

// TechnicianIDGTE applies the GTE predicate on the "technician_id" field.
func TechnicianIDGTE(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldTechnicianID, v))
}

// TechnicianIDLT applies the LT predicate on the "technician_id" field.
func TechnicianIDLT(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldTechnicianID, v))
}

// TechnicianIDLTE applies the LTE predicate on the "technician_id" field.
func TechnicianIDLTE(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldTechnicianID, v))
}

// TechnicianIDIsNil applies the IsNil predicate on the "technician_id" field.
func TechnicianIDIsNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIsNull(FieldTechnicianID))
}

// TechnicianIDNotNil applies the NotNil predicate on the "technician_id" field.
func TechnicianIDNotNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotNull(FieldTechnicianID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldStatus, vs...))
}

// WorkTypeEQ applies the EQ predicate on the "work_type" field.
func WorkTypeEQ(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldWorkType, v))
}

// WorkTypeNEQ applies the NEQ predicate on the "work_type" field.
func WorkTypeNEQ(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldWorkType, v))
}

// WorkTypeIn applies the In predicate on the "work_type" field.
func WorkTypeIn(vs ...string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldWorkType, vs...))
}

// WorkTypeNotIn applies the NotIn predicate on the "work_type" field.
func WorkTypeNotIn(vs ...string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldWorkType, vs...))
}

// WorkTypeGT applies the GT predicate on the "work_type" field.
func WorkTypeGT(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldWorkType, v))
}

// WorkTypeGTE applies the GTE predicate on the "work_type" field.
func WorkTypeGTE(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldWorkType, v))
}

// WorkTypeLT applies the LT predicate on the "work_type" field.
func WorkTypeLT(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldWorkType, v))
}

// WorkTypeLTE applies the LTE predicate on the "work_type" field.
func WorkTypeLTE(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldWorkType, v))
}

// WorkTypeContains applies the Contains predicate on the "work_type" field.
func WorkTypeContains(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldContains(FieldWorkType, v))
}

// WorkTypeHasPrefix applies the HasPrefix predicate on the "work_type" field.
func WorkTypeHasPrefix(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldHasPrefix(FieldWorkType, v))
}

// WorkTypeHasSuffix applies the HasSuffix predicate on the "work_type" field.
func WorkTypeHasSuffix(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldHasSuffix(FieldWorkType, v))
}

// WorkTypeEqualFold applies the EqualFold predicate on the "work_type" field.
func WorkTypeEqualFold(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEqualFold(FieldWorkType, v))
}

// WorkTypeContainsFold applies the ContainsFold predicate on the "work_type" field.
func WorkTypeContainsFold(v string) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldContainsFold(FieldWorkType, v))
}

// DurationHoursEQ applies the EQ predicate on the "duration_hours" field.
func DurationHoursEQ(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldDurationHours, v))
}

// DurationHoursNEQ applies the NEQ predicate on the "duration_hours" field.
func DurationHoursNEQ(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldDurationHours, v))
}

// DurationHoursIn applies the In predicate on the "duration_hours" field.
func DurationHoursIn(vs ...float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldDurationHours, vs...))
}

// DurationHoursNotIn applies the NotIn predicate on the "duration_hours" field.
func DurationHoursNotIn(vs ...float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldDurationHours, vs...))
}

// DurationHoursGT applies the GT predicate on the "duration_hours" field.
func DurationHoursGT(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldDurationHours, v))
}

// DurationHoursGTE applies the GTE predicate on the "duration_hours" field.
func DurationHoursGTE(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldDurationHours, v))
}

// DurationHoursLT applies the LT predicate on the "duration_hours" field.
func DurationHoursLT(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldDurationHours, v))
}

// DurationHoursLTE applies the LTE predicate on the "duration_hours" field.
func DurationHoursLTE(v float64) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldDurationHours, v))
}

// DurationHoursIsNil applies the IsNil predicate on the "duration_hours" field.
func DurationHoursIsNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIsNull(FieldDurationHours))
}

// DurationHoursNotNil applies the NotNil predicate on the "duration_hours" field.
func DurationHoursNotNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotNull(FieldDurationHours))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v int) predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldLTE(FieldInvoiceID, v))
}

// InvoiceIDIsNil applies the IsNil predicate on the "invoice_id" field.
func InvoiceIDIsNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldIsNull(FieldInvoiceID))
}

// InvoiceIDNotNil applies the NotNil predicate on the "invoice_id" field.
func InvoiceIDNotNil() predicate.TimeEntry {
	return predicate.TimeEntry(sql.FieldNotNull(FieldInvoiceID))
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.TimeEntry {
	return predicate.TimeEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.TimeEntry {
	return predicate.TimeEntry(func(s *sql.Selector) {
		step := newEmployeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TimeEntry {
	return predicate.TimeEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TimeEntry {
	return predicate.TimeEntry(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TimeEntry) predicate.TimeEntry {
	return predicate.TimeEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TimeEntry) predicate.TimeEntry {
	return predicate.TimeEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TimeEntry) predicate.TimeEntry {
	return predicate.TimeEntry(sql.NotPredicates(p))
}
