// Code generated by ent, DO NOT EDIT.

package camera

import (
	"sent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldName, v))
}

// RtspURL applies equality check predicate on the "rtsp_url" field. It's identical to RtspURLEQ.
func RtspURL(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldRtspURL, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldIPAddress, v))
}

// OnvifPort applies equality check predicate on the "onvif_port" field. It's identical to OnvifPortEQ.
func OnvifPort(v int) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldOnvifPort, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldPassword, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContainsFold(FieldName, v))
}

// RtspURLEQ applies the EQ predicate on the "rtsp_url" field.
func RtspURLEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldRtspURL, v))
}

// RtspURLNEQ applies the NEQ predicate on the "rtsp_url" field.
func RtspURLNEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldRtspURL, v))
}

// RtspURLIn applies the In predicate on the "rtsp_url" field.
func RtspURLIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldRtspURL, vs...))
}

// RtspURLNotIn applies the NotIn predicate on the "rtsp_url" field.
func RtspURLNotIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldRtspURL, vs...))
}

// RtspURLGT applies the GT predicate on the "rtsp_url" field.
func RtspURLGT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldRtspURL, v))
}

// RtspURLGTE applies the GTE predicate on the "rtsp_url" field.
func RtspURLGTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldRtspURL, v))
}

// RtspURLLT applies the LT predicate on the "rtsp_url" field.
func RtspURLLT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldRtspURL, v))
}

// RtspURLLTE applies the LTE predicate on the "rtsp_url" field.
func RtspURLLTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldRtspURL, v))
}

// RtspURLContains applies the Contains predicate on the "rtsp_url" field.
func RtspURLContains(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContains(FieldRtspURL, v))
}

// RtspURLHasPrefix applies the HasPrefix predicate on the "rtsp_url" field.
func RtspURLHasPrefix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasPrefix(FieldRtspURL, v))
}

// RtspURLHasSuffix applies the HasSuffix predicate on the "rtsp_url" field.
func RtspURLHasSuffix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasSuffix(FieldRtspURL, v))
}

// RtspURLEqualFold applies the EqualFold predicate on the "rtsp_url" field.
func RtspURLEqualFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEqualFold(FieldRtspURL, v))
}

// RtspURLContainsFold applies the ContainsFold predicate on the "rtsp_url" field.
func RtspURLContainsFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContainsFold(FieldRtspURL, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.Camera {
	return predicate.Camera(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.Camera {
	return predicate.Camera(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContainsFold(FieldIPAddress, v))
}

// OnvifPortEQ applies the EQ predicate on the "onvif_port" field.
func OnvifPortEQ(v int) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldOnvifPort, v))
}

// OnvifPortNEQ applies the NEQ predicate on the "onvif_port" field.
func OnvifPortNEQ(v int) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldOnvifPort, v))
}

// OnvifPortIn applies the In predicate on the "onvif_port" field.
func OnvifPortIn(vs ...int) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldOnvifPort, vs...))
}

// OnvifPortNotIn applies the NotIn predicate on the "onvif_port" field.
func OnvifPortNotIn(vs ...int) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldOnvifPort, vs...))
}

// OnvifPortGT applies the GT predicate on the "onvif_port" field.
func OnvifPortGT(v int) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldOnvifPort, v))
}

// OnvifPortGTE applies the GTE predicate on the "onvif_port" field.
func OnvifPortGTE(v int) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldOnvifPort, v))
}

// OnvifPortLT applies the LT predicate on the "onvif_port" field.
func OnvifPortLT(v int) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldOnvifPort, v))
}

// OnvifPortLTE applies the LTE predicate on the "onvif_port" field.
func OnvifPortLTE(v int) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldOnvifPort, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.Camera {
	return predicate.Camera(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.Camera {
	return predicate.Camera(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Camera {
	return predicate.Camera(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Camera {
	return predicate.Camera(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Camera {
	return predicate.Camera(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Camera {
	return predicate.Camera(sql.FieldContainsFold(FieldPassword, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Camera {
	return predicate.Camera(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Camera {
	return predicate.Camera(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Camera {
	return predicate.Camera(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecordings applies the HasEdge predicate on the "recordings" edge.
func HasRecordings() predicate.Camera {
	return predicate.Camera(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordingsTable, RecordingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordingsWith applies the HasEdge predicate on the "recordings" edge with a given conditions (other predicates).
func HasRecordingsWith(preds ...predicate.Recording) predicate.Camera {
	return predicate.Camera(func(s *sql.Selector) {
		step := newRecordingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDetections applies the HasEdge predicate on the "detections" edge.
func HasDetections() predicate.Camera {
	return predicate.Camera(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DetectionsTable, DetectionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDetectionsWith applies the HasEdge predicate on the "detections" edge with a given conditions (other predicates).
func HasDetectionsWith(preds ...predicate.DetectionEvent) predicate.Camera {
	return predicate.Camera(func(s *sql.Selector) {
		step := newDetectionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Camera) predicate.Camera {
	return predicate.Camera(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Camera) predicate.Camera {
	return predicate.Camera(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Camera) predicate.Camera {
	return predicate.Camera(sql.NotPredicates(p))
}
