// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/assetassignment"
	"sent/ent/employee"
	"sent/ent/product"
	"sent/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssetAssignmentCreate is the builder for creating a AssetAssignment entity.
type AssetAssignmentCreate struct {
	config
	mutation *AssetAssignmentMutation
	hooks    []Hook
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *AssetAssignmentCreate) SetAssignedAt(v time.Time) *AssetAssignmentCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableAssignedAt(v *time.Time) *AssetAssignmentCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetReturnedAt sets the "returned_at" field.
func (_c *AssetAssignmentCreate) SetReturnedAt(v time.Time) *AssetAssignmentCreate {
	_c.mutation.SetReturnedAt(v)
	return _c
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableReturnedAt(v *time.Time) *AssetAssignmentCreate {
	if v != nil {
		_c.SetReturnedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AssetAssignmentCreate) SetStatus(v assetassignment.Status) *AssetAssignmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableStatus(v *assetassignment.Status) *AssetAssignmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *AssetAssignmentCreate) SetQuantity(v int) *AssetAssignmentCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *AssetAssignmentCreate) SetNillableQuantity(v *int) *AssetAssignmentCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *AssetAssignmentCreate) SetTenantID(id int) *AssetAssignmentCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *AssetAssignmentCreate) SetTenant(v *Tenant) *AssetAssignmentCreate {
	return _c.SetTenantID(v.ID)
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_c *AssetAssignmentCreate) SetProductID(id int) *AssetAssignmentCreate {
	_c.mutation.SetProductID(id)
	return _c
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *AssetAssignmentCreate) SetProduct(v *Product) *AssetAssignmentCreate {
	return _c.SetProductID(v.ID)
}

// SetEmployeeID sets the "employee" edge to the Employee entity by ID.
func (_c *AssetAssignmentCreate) SetEmployeeID(id int) *AssetAssignmentCreate {
	_c.mutation.SetEmployeeID(id)
	return _c
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *AssetAssignmentCreate) SetEmployee(v *Employee) *AssetAssignmentCreate {
	return _c.SetEmployeeID(v.ID)
}

// Mutation returns the AssetAssignmentMutation object of the builder.
func (_c *AssetAssignmentCreate) Mutation() *AssetAssignmentMutation {
	return _c.mutation
}

// Save creates the AssetAssignment in the database.
func (_c *AssetAssignmentCreate) Save(ctx context.Context) (*AssetAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetAssignmentCreate) SaveX(ctx context.Context) *AssetAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetAssignmentCreate) defaults() {
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := assetassignment.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := assetassignment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		v := assetassignment.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetAssignmentCreate) check() error {
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "AssetAssignment.assigned_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AssetAssignment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := assetassignment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AssetAssignment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "AssetAssignment.quantity"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "AssetAssignment.tenant"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "AssetAssignment.product"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "AssetAssignment.employee"`)}
	}
	return nil
}

func (_c *AssetAssignmentCreate) sqlSave(ctx context.Context) (*AssetAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetAssignmentCreate) createSpec() (*AssetAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assetassignment.Table, sqlgraph.NewFieldSpec(assetassignment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(assetassignment.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.ReturnedAt(); ok {
		_spec.SetField(assetassignment.FieldReturnedAt, field.TypeTime, value)
		_node.ReturnedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(assetassignment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(assetassignment.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assetassignment.TenantTable,
			Columns: []string{assetassignment.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_asset_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assetassignment.ProductTable,
			Columns: []string{assetassignment.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.product_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assetassignment.EmployeeTable,
			Columns: []string{assetassignment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.employee_asset_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetAssignmentCreateBulk is the builder for creating many AssetAssignment entities in bulk.
type AssetAssignmentCreateBulk struct {
	config
	err      error
	builders []*AssetAssignmentCreate
}

// Save creates the AssetAssignment entities in the database.
func (_c *AssetAssignmentCreateBulk) Save(ctx context.Context) ([]*AssetAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AssetAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetAssignmentCreateBulk) SaveX(ctx context.Context) []*AssetAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
