// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/asset"
	"sent/ent/assettype"
	"sent/ent/credential"
	"sent/ent/product"
	"sent/ent/sop"
	"sent/ent/tenant"
	"sent/ent/ticket"
	"sent/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AssetCreate) SetName(v string) *AssetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetHardwareID sets the "hardware_id" field.
func (_c *AssetCreate) SetHardwareID(v string) *AssetCreate {
	_c.mutation.SetHardwareID(v)
	return _c
}

// SetNillableHardwareID sets the "hardware_id" field if the given value is not nil.
func (_c *AssetCreate) SetNillableHardwareID(v *string) *AssetCreate {
	if v != nil {
		_c.SetHardwareID(*v)
	}
	return _c
}

// SetSerialNumber sets the "serial_number" field.
func (_c *AssetCreate) SetSerialNumber(v string) *AssetCreate {
	_c.mutation.SetSerialNumber(v)
	return _c
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_c *AssetCreate) SetNillableSerialNumber(v *string) *AssetCreate {
	if v != nil {
		_c.SetSerialNumber(*v)
	}
	return _c
}

// SetManufacturer sets the "manufacturer" field.
func (_c *AssetCreate) SetManufacturer(v string) *AssetCreate {
	_c.mutation.SetManufacturer(v)
	return _c
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_c *AssetCreate) SetNillableManufacturer(v *string) *AssetCreate {
	if v != nil {
		_c.SetManufacturer(*v)
	}
	return _c
}

// SetVendorSupportPhone sets the "vendor_support_phone" field.
func (_c *AssetCreate) SetVendorSupportPhone(v string) *AssetCreate {
	_c.mutation.SetVendorSupportPhone(v)
	return _c
}

// SetNillableVendorSupportPhone sets the "vendor_support_phone" field if the given value is not nil.
func (_c *AssetCreate) SetNillableVendorSupportPhone(v *string) *AssetCreate {
	if v != nil {
		_c.SetVendorSupportPhone(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AssetCreate) SetStatus(v asset.Status) *AssetCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AssetCreate) SetNillableStatus(v *asset.Status) *AssetCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AssetCreate) SetMetadata(v map[string]interface{}) *AssetCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetLastCertifiedAt sets the "last_certified_at" field.
func (_c *AssetCreate) SetLastCertifiedAt(v time.Time) *AssetCreate {
	_c.mutation.SetLastCertifiedAt(v)
	return _c
}

// SetNillableLastCertifiedAt sets the "last_certified_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableLastCertifiedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetLastCertifiedAt(*v)
	}
	return _c
}

// SetPurchaseDate sets the "purchase_date" field.
func (_c *AssetCreate) SetPurchaseDate(v time.Time) *AssetCreate {
	_c.mutation.SetPurchaseDate(v)
	return _c
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_c *AssetCreate) SetNillablePurchaseDate(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetPurchaseDate(*v)
	}
	return _c
}

// SetWarrantyExpiry sets the "warranty_expiry" field.
func (_c *AssetCreate) SetWarrantyExpiry(v time.Time) *AssetCreate {
	_c.mutation.SetWarrantyExpiry(v)
	return _c
}

// SetNillableWarrantyExpiry sets the "warranty_expiry" field if the given value is not nil.
func (_c *AssetCreate) SetNillableWarrantyExpiry(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetWarrantyExpiry(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AssetCreate) SetCreatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableCreatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AssetCreate) SetUpdatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableUpdatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *AssetCreate) SetTenantID(id int) *AssetCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *AssetCreate) SetTenant(v *Tenant) *AssetCreate {
	return _c.SetTenantID(v.ID)
}

// SetTypeID sets the "type" edge to the AssetType entity by ID.
func (_c *AssetCreate) SetTypeID(id int) *AssetCreate {
	_c.mutation.SetTypeID(id)
	return _c
}

// SetType sets the "type" edge to the AssetType entity.
func (_c *AssetCreate) SetType(v *AssetType) *AssetCreate {
	return _c.SetTypeID(v.ID)
}

// SetHostedAtID sets the "hosted_at" edge to the Asset entity by ID.
func (_c *AssetCreate) SetHostedAtID(id int) *AssetCreate {
	_c.mutation.SetHostedAtID(id)
	return _c
}

// SetNillableHostedAtID sets the "hosted_at" edge to the Asset entity by ID if the given value is not nil.
func (_c *AssetCreate) SetNillableHostedAtID(id *int) *AssetCreate {
	if id != nil {
		_c = _c.SetHostedAtID(*id)
	}
	return _c
}

// SetHostedAt sets the "hosted_at" edge to the Asset entity.
func (_c *AssetCreate) SetHostedAt(v *Asset) *AssetCreate {
	return _c.SetHostedAtID(v.ID)
}

// AddHostedAssetIDs adds the "hosted_assets" edge to the Asset entity by IDs.
func (_c *AssetCreate) AddHostedAssetIDs(ids ...int) *AssetCreate {
	_c.mutation.AddHostedAssetIDs(ids...)
	return _c
}

// AddHostedAssets adds the "hosted_assets" edges to the Asset entity.
func (_c *AssetCreate) AddHostedAssets(v ...*Asset) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddHostedAssetIDs(ids...)
}

// AddDependencyOfIDs adds the "dependency_of" edge to the Asset entity by IDs.
func (_c *AssetCreate) AddDependencyOfIDs(ids ...int) *AssetCreate {
	_c.mutation.AddDependencyOfIDs(ids...)
	return _c
}

// AddDependencyOf adds the "dependency_of" edges to the Asset entity.
func (_c *AssetCreate) AddDependencyOf(v ...*Asset) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDependencyOfIDs(ids...)
}

// AddDependsOnIDs adds the "depends_on" edge to the Asset entity by IDs.
func (_c *AssetCreate) AddDependsOnIDs(ids ...int) *AssetCreate {
	_c.mutation.AddDependsOnIDs(ids...)
	return _c
}

// AddDependsOn adds the "depends_on" edges to the Asset entity.
func (_c *AssetCreate) AddDependsOn(v ...*Asset) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDependsOnIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *AssetCreate) SetOwnerID(id int) *AssetCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *AssetCreate) SetNillableOwnerID(id *int) *AssetCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *AssetCreate) SetOwner(v *User) *AssetCreate {
	return _c.SetOwnerID(v.ID)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_c *AssetCreate) AddCredentialIDs(ids ...int) *AssetCreate {
	_c.mutation.AddCredentialIDs(ids...)
	return _c
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_c *AssetCreate) AddCredentials(v ...*Credential) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCredentialIDs(ids...)
}

// AddSopIDs adds the "sops" edge to the SOP entity by IDs.
func (_c *AssetCreate) AddSopIDs(ids ...int) *AssetCreate {
	_c.mutation.AddSopIDs(ids...)
	return _c
}

// AddSops adds the "sops" edges to the SOP entity.
func (_c *AssetCreate) AddSops(v ...*SOP) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSopIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *AssetCreate) AddTicketIDs(ids ...int) *AssetCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *AssetCreate) AddTickets(v ...*Ticket) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_c *AssetCreate) SetProductID(id int) *AssetCreate {
	_c.mutation.SetProductID(id)
	return _c
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (_c *AssetCreate) SetNillableProductID(id *int) *AssetCreate {
	if id != nil {
		_c = _c.SetProductID(*id)
	}
	return _c
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *AssetCreate) SetProduct(v *Product) *AssetCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the AssetMutation object of the builder.
func (_c *AssetCreate) Mutation() *AssetMutation {
	return _c.mutation
}

// Save creates the Asset in the database.
func (_c *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := asset.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := asset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := asset.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Asset.name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Asset.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := asset.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Asset.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Asset.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Asset.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Asset.tenant"`)}
	}
	if len(_c.mutation.TypeIDs()) == 0 {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required edge "Asset.type"`)}
	}
	return nil
}

func (_c *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(asset.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.HardwareID(); ok {
		_spec.SetField(asset.FieldHardwareID, field.TypeString, value)
		_node.HardwareID = value
	}
	if value, ok := _c.mutation.SerialNumber(); ok {
		_spec.SetField(asset.FieldSerialNumber, field.TypeString, value)
		_node.SerialNumber = value
	}
	if value, ok := _c.mutation.Manufacturer(); ok {
		_spec.SetField(asset.FieldManufacturer, field.TypeString, value)
		_node.Manufacturer = value
	}
	if value, ok := _c.mutation.VendorSupportPhone(); ok {
		_spec.SetField(asset.FieldVendorSupportPhone, field.TypeString, value)
		_node.VendorSupportPhone = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(asset.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(asset.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.LastCertifiedAt(); ok {
		_spec.SetField(asset.FieldLastCertifiedAt, field.TypeTime, value)
		_node.LastCertifiedAt = value
	}
	if value, ok := _c.mutation.PurchaseDate(); ok {
		_spec.SetField(asset.FieldPurchaseDate, field.TypeTime, value)
		_node.PurchaseDate = value
	}
	if value, ok := _c.mutation.WarrantyExpiry(); ok {
		_spec.SetField(asset.FieldWarrantyExpiry, field.TypeTime, value)
		_node.WarrantyExpiry = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TenantTable,
			Columns: []string{asset.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_assets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TypeTable,
			Columns: []string{asset.TypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.asset_type_assets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HostedAtIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.HostedAtTable,
			Columns: []string{asset.HostedAtColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.asset_hosted_assets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HostedAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.HostedAssetsTable,
			Columns: []string{asset.HostedAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DependencyOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.DependencyOfTable,
			Columns: asset.DependencyOfPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DependsOnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.DependsOnTable,
			Columns: asset.DependsOnPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.OwnerTable,
			Columns: []string{asset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_owned_assets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CredentialsTable,
			Columns: []string{asset.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.SopsTable,
			Columns: []string{asset.SopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.TicketsTable,
			Columns: []string{asset.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   asset.ProductTable,
			Columns: []string{asset.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.asset_product = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
}

// Save creates the Asset entities in the database.
func (_c *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
