// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/benefitenrollment"
	"sent/ent/benefitplan"
	"sent/ent/employee"
	"sent/ent/predicate"
	"sent/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BenefitEnrollmentUpdate is the builder for updating BenefitEnrollment entities.
type BenefitEnrollmentUpdate struct {
	config
	hooks     []Hook
	mutation  *BenefitEnrollmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BenefitEnrollmentUpdate builder.
func (_u *BenefitEnrollmentUpdate) Where(ps ...predicate.BenefitEnrollment) *BenefitEnrollmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTier sets the "tier" field.
func (_u *BenefitEnrollmentUpdate) SetTier(v benefitenrollment.Tier) *BenefitEnrollmentUpdate {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdate) SetNillableTier(v *benefitenrollment.Tier) *BenefitEnrollmentUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetEmployeeCost sets the "employee_cost" field.
func (_u *BenefitEnrollmentUpdate) SetEmployeeCost(v float64) *BenefitEnrollmentUpdate {
	_u.mutation.ResetEmployeeCost()
	_u.mutation.SetEmployeeCost(v)
	return _u
}

// SetNillableEmployeeCost sets the "employee_cost" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdate) SetNillableEmployeeCost(v *float64) *BenefitEnrollmentUpdate {
	if v != nil {
		_u.SetEmployeeCost(*v)
	}
	return _u
}

// AddEmployeeCost adds value to the "employee_cost" field.
func (_u *BenefitEnrollmentUpdate) AddEmployeeCost(v float64) *BenefitEnrollmentUpdate {
	_u.mutation.AddEmployeeCost(v)
	return _u
}

// SetEmployerCost sets the "employer_cost" field.
func (_u *BenefitEnrollmentUpdate) SetEmployerCost(v float64) *BenefitEnrollmentUpdate {
	_u.mutation.ResetEmployerCost()
	_u.mutation.SetEmployerCost(v)
	return _u
}

// SetNillableEmployerCost sets the "employer_cost" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdate) SetNillableEmployerCost(v *float64) *BenefitEnrollmentUpdate {
	if v != nil {
		_u.SetEmployerCost(*v)
	}
	return _u
}

// AddEmployerCost adds value to the "employer_cost" field.
func (_u *BenefitEnrollmentUpdate) AddEmployerCost(v float64) *BenefitEnrollmentUpdate {
	_u.mutation.AddEmployerCost(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BenefitEnrollmentUpdate) SetStatus(v benefitenrollment.Status) *BenefitEnrollmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdate) SetNillableStatus(v *benefitenrollment.Status) *BenefitEnrollmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *BenefitEnrollmentUpdate) SetEffectiveFrom(v time.Time) *BenefitEnrollmentUpdate {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdate) SetNillableEffectiveFrom(v *time.Time) *BenefitEnrollmentUpdate {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetEffectiveTo sets the "effective_to" field.
func (_u *BenefitEnrollmentUpdate) SetEffectiveTo(v time.Time) *BenefitEnrollmentUpdate {
	_u.mutation.SetEffectiveTo(v)
	return _u
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdate) SetNillableEffectiveTo(v *time.Time) *BenefitEnrollmentUpdate {
	if v != nil {
		_u.SetEffectiveTo(*v)
	}
	return _u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (_u *BenefitEnrollmentUpdate) ClearEffectiveTo() *BenefitEnrollmentUpdate {
	_u.mutation.ClearEffectiveTo()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitEnrollmentUpdate) SetUpdatedAt(v time.Time) *BenefitEnrollmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *BenefitEnrollmentUpdate) SetTenantID(id int) *BenefitEnrollmentUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *BenefitEnrollmentUpdate) SetTenant(v *Tenant) *BenefitEnrollmentUpdate {
	return _u.SetTenantID(v.ID)
}

// SetPlanID sets the "plan" edge to the BenefitPlan entity by ID.
func (_u *BenefitEnrollmentUpdate) SetPlanID(id int) *BenefitEnrollmentUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the BenefitPlan entity.
func (_u *BenefitEnrollmentUpdate) SetPlan(v *BenefitPlan) *BenefitEnrollmentUpdate {
	return _u.SetPlanID(v.ID)
}

// SetEmployeeID sets the "employee" edge to the Employee entity by ID.
func (_u *BenefitEnrollmentUpdate) SetEmployeeID(id int) *BenefitEnrollmentUpdate {
	_u.mutation.SetEmployeeID(id)
	return _u
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *BenefitEnrollmentUpdate) SetEmployee(v *Employee) *BenefitEnrollmentUpdate {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the BenefitEnrollmentMutation object of the builder.
func (_u *BenefitEnrollmentUpdate) Mutation() *BenefitEnrollmentMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *BenefitEnrollmentUpdate) ClearTenant() *BenefitEnrollmentUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearPlan clears the "plan" edge to the BenefitPlan entity.
func (_u *BenefitEnrollmentUpdate) ClearPlan() *BenefitEnrollmentUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *BenefitEnrollmentUpdate) ClearEmployee() *BenefitEnrollmentUpdate {
	_u.mutation.ClearEmployee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BenefitEnrollmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitEnrollmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BenefitEnrollmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitEnrollmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitEnrollmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := benefitenrollment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitEnrollmentUpdate) check() error {
	if v, ok := _u.mutation.Tier(); ok {
		if err := benefitenrollment.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BenefitEnrollment.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := benefitenrollment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitEnrollment.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitEnrollment.tenant"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitEnrollment.plan"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitEnrollment.employee"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BenefitEnrollmentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BenefitEnrollmentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BenefitEnrollmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitenrollment.Table, benefitenrollment.Columns, sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(benefitenrollment.FieldTier, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EmployeeCost(); ok {
		_spec.SetField(benefitenrollment.FieldEmployeeCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployeeCost(); ok {
		_spec.AddField(benefitenrollment.FieldEmployeeCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EmployerCost(); ok {
		_spec.SetField(benefitenrollment.FieldEmployerCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployerCost(); ok {
		_spec.AddField(benefitenrollment.FieldEmployerCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(benefitenrollment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(benefitenrollment.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EffectiveTo(); ok {
		_spec.SetField(benefitenrollment.FieldEffectiveTo, field.TypeTime, value)
	}
	if _u.mutation.EffectiveToCleared() {
		_spec.ClearField(benefitenrollment.FieldEffectiveTo, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitenrollment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.TenantTable,
			Columns: []string{benefitenrollment.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.TenantTable,
			Columns: []string{benefitenrollment.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.PlanTable,
			Columns: []string{benefitenrollment.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.PlanTable,
			Columns: []string{benefitenrollment.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.EmployeeTable,
			Columns: []string{benefitenrollment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.EmployeeTable,
			Columns: []string{benefitenrollment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitenrollment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BenefitEnrollmentUpdateOne is the builder for updating a single BenefitEnrollment entity.
type BenefitEnrollmentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BenefitEnrollmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTier sets the "tier" field.
func (_u *BenefitEnrollmentUpdateOne) SetTier(v benefitenrollment.Tier) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdateOne) SetNillableTier(v *benefitenrollment.Tier) *BenefitEnrollmentUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetEmployeeCost sets the "employee_cost" field.
func (_u *BenefitEnrollmentUpdateOne) SetEmployeeCost(v float64) *BenefitEnrollmentUpdateOne {
	_u.mutation.ResetEmployeeCost()
	_u.mutation.SetEmployeeCost(v)
	return _u
}

// SetNillableEmployeeCost sets the "employee_cost" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdateOne) SetNillableEmployeeCost(v *float64) *BenefitEnrollmentUpdateOne {
	if v != nil {
		_u.SetEmployeeCost(*v)
	}
	return _u
}

// AddEmployeeCost adds value to the "employee_cost" field.
func (_u *BenefitEnrollmentUpdateOne) AddEmployeeCost(v float64) *BenefitEnrollmentUpdateOne {
	_u.mutation.AddEmployeeCost(v)
	return _u
}

// SetEmployerCost sets the "employer_cost" field.
func (_u *BenefitEnrollmentUpdateOne) SetEmployerCost(v float64) *BenefitEnrollmentUpdateOne {
	_u.mutation.ResetEmployerCost()
	_u.mutation.SetEmployerCost(v)
	return _u
}

// SetNillableEmployerCost sets the "employer_cost" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdateOne) SetNillableEmployerCost(v *float64) *BenefitEnrollmentUpdateOne {
	if v != nil {
		_u.SetEmployerCost(*v)
	}
	return _u
}

// AddEmployerCost adds value to the "employer_cost" field.
func (_u *BenefitEnrollmentUpdateOne) AddEmployerCost(v float64) *BenefitEnrollmentUpdateOne {
	_u.mutation.AddEmployerCost(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BenefitEnrollmentUpdateOne) SetStatus(v benefitenrollment.Status) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdateOne) SetNillableStatus(v *benefitenrollment.Status) *BenefitEnrollmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *BenefitEnrollmentUpdateOne) SetEffectiveFrom(v time.Time) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdateOne) SetNillableEffectiveFrom(v *time.Time) *BenefitEnrollmentUpdateOne {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetEffectiveTo sets the "effective_to" field.
func (_u *BenefitEnrollmentUpdateOne) SetEffectiveTo(v time.Time) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetEffectiveTo(v)
	return _u
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_u *BenefitEnrollmentUpdateOne) SetNillableEffectiveTo(v *time.Time) *BenefitEnrollmentUpdateOne {
	if v != nil {
		_u.SetEffectiveTo(*v)
	}
	return _u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (_u *BenefitEnrollmentUpdateOne) ClearEffectiveTo() *BenefitEnrollmentUpdateOne {
	_u.mutation.ClearEffectiveTo()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitEnrollmentUpdateOne) SetUpdatedAt(v time.Time) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *BenefitEnrollmentUpdateOne) SetTenantID(id int) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *BenefitEnrollmentUpdateOne) SetTenant(v *Tenant) *BenefitEnrollmentUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetPlanID sets the "plan" edge to the BenefitPlan entity by ID.
func (_u *BenefitEnrollmentUpdateOne) SetPlanID(id int) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the BenefitPlan entity.
func (_u *BenefitEnrollmentUpdateOne) SetPlan(v *BenefitPlan) *BenefitEnrollmentUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetEmployeeID sets the "employee" edge to the Employee entity by ID.
func (_u *BenefitEnrollmentUpdateOne) SetEmployeeID(id int) *BenefitEnrollmentUpdateOne {
	_u.mutation.SetEmployeeID(id)
	return _u
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *BenefitEnrollmentUpdateOne) SetEmployee(v *Employee) *BenefitEnrollmentUpdateOne {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the BenefitEnrollmentMutation object of the builder.
func (_u *BenefitEnrollmentUpdateOne) Mutation() *BenefitEnrollmentMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *BenefitEnrollmentUpdateOne) ClearTenant() *BenefitEnrollmentUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearPlan clears the "plan" edge to the BenefitPlan entity.
func (_u *BenefitEnrollmentUpdateOne) ClearPlan() *BenefitEnrollmentUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *BenefitEnrollmentUpdateOne) ClearEmployee() *BenefitEnrollmentUpdateOne {
	_u.mutation.ClearEmployee()
	return _u
}

// Where appends a list predicates to the BenefitEnrollmentUpdate builder.
func (_u *BenefitEnrollmentUpdateOne) Where(ps ...predicate.BenefitEnrollment) *BenefitEnrollmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BenefitEnrollmentUpdateOne) Select(field string, fields ...string) *BenefitEnrollmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BenefitEnrollment entity.
func (_u *BenefitEnrollmentUpdateOne) Save(ctx context.Context) (*BenefitEnrollment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitEnrollmentUpdateOne) SaveX(ctx context.Context) *BenefitEnrollment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BenefitEnrollmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitEnrollmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitEnrollmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := benefitenrollment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitEnrollmentUpdateOne) check() error {
	if v, ok := _u.mutation.Tier(); ok {
		if err := benefitenrollment.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "BenefitEnrollment.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := benefitenrollment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitEnrollment.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitEnrollment.tenant"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitEnrollment.plan"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitEnrollment.employee"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BenefitEnrollmentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BenefitEnrollmentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BenefitEnrollmentUpdateOne) sqlSave(ctx context.Context) (_node *BenefitEnrollment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitenrollment.Table, benefitenrollment.Columns, sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BenefitEnrollment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitenrollment.FieldID)
		for _, f := range fields {
			if !benefitenrollment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefitenrollment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(benefitenrollment.FieldTier, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EmployeeCost(); ok {
		_spec.SetField(benefitenrollment.FieldEmployeeCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployeeCost(); ok {
		_spec.AddField(benefitenrollment.FieldEmployeeCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EmployerCost(); ok {
		_spec.SetField(benefitenrollment.FieldEmployerCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployerCost(); ok {
		_spec.AddField(benefitenrollment.FieldEmployerCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(benefitenrollment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(benefitenrollment.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EffectiveTo(); ok {
		_spec.SetField(benefitenrollment.FieldEffectiveTo, field.TypeTime, value)
	}
	if _u.mutation.EffectiveToCleared() {
		_spec.ClearField(benefitenrollment.FieldEffectiveTo, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitenrollment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.TenantTable,
			Columns: []string{benefitenrollment.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.TenantTable,
			Columns: []string{benefitenrollment.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.PlanTable,
			Columns: []string{benefitenrollment.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.PlanTable,
			Columns: []string{benefitenrollment.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.EmployeeTable,
			Columns: []string{benefitenrollment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitenrollment.EmployeeTable,
			Columns: []string{benefitenrollment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BenefitEnrollment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitenrollment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
