// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/benefitenrollment"
	"sent/ent/benefitplan"
	"sent/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BenefitPlanCreate is the builder for creating a BenefitPlan entity.
type BenefitPlanCreate struct {
	config
	mutation *BenefitPlanMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *BenefitPlanCreate) SetName(v string) *BenefitPlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BenefitPlanCreate) SetDescription(v string) *BenefitPlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BenefitPlanCreate) SetNillableDescription(v *string) *BenefitPlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *BenefitPlanCreate) SetType(v benefitplan.Type) *BenefitPlanCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *BenefitPlanCreate) SetNillableType(v *benefitplan.Type) *BenefitPlanCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BenefitPlanCreate) SetStatus(v benefitplan.Status) *BenefitPlanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BenefitPlanCreate) SetNillableStatus(v *benefitplan.Status) *BenefitPlanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEmployerContribution sets the "employer_contribution" field.
func (_c *BenefitPlanCreate) SetEmployerContribution(v float64) *BenefitPlanCreate {
	_c.mutation.SetEmployerContribution(v)
	return _c
}

// SetEmployeeDeduction sets the "employee_deduction" field.
func (_c *BenefitPlanCreate) SetEmployeeDeduction(v float64) *BenefitPlanCreate {
	_c.mutation.SetEmployeeDeduction(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BenefitPlanCreate) SetCreatedAt(v time.Time) *BenefitPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BenefitPlanCreate) SetNillableCreatedAt(v *time.Time) *BenefitPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BenefitPlanCreate) SetUpdatedAt(v time.Time) *BenefitPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BenefitPlanCreate) SetNillableUpdatedAt(v *time.Time) *BenefitPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *BenefitPlanCreate) SetTenantID(id int) *BenefitPlanCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *BenefitPlanCreate) SetTenant(v *Tenant) *BenefitPlanCreate {
	return _c.SetTenantID(v.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the BenefitEnrollment entity by IDs.
func (_c *BenefitPlanCreate) AddEnrollmentIDs(ids ...int) *BenefitPlanCreate {
	_c.mutation.AddEnrollmentIDs(ids...)
	return _c
}

// AddEnrollments adds the "enrollments" edges to the BenefitEnrollment entity.
func (_c *BenefitPlanCreate) AddEnrollments(v ...*BenefitEnrollment) *BenefitPlanCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEnrollmentIDs(ids...)
}

// Mutation returns the BenefitPlanMutation object of the builder.
func (_c *BenefitPlanCreate) Mutation() *BenefitPlanMutation {
	return _c.mutation
}

// Save creates the BenefitPlan in the database.
func (_c *BenefitPlanCreate) Save(ctx context.Context) (*BenefitPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BenefitPlanCreate) SaveX(ctx context.Context) *BenefitPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BenefitPlanCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := benefitplan.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := benefitplan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := benefitplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := benefitplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BenefitPlanCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BenefitPlan.name"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "BenefitPlan.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := benefitplan.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BenefitPlan.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BenefitPlan.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := benefitplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitPlan.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmployerContribution(); !ok {
		return &ValidationError{Name: "employer_contribution", err: errors.New(`ent: missing required field "BenefitPlan.employer_contribution"`)}
	}
	if _, ok := _c.mutation.EmployeeDeduction(); !ok {
		return &ValidationError{Name: "employee_deduction", err: errors.New(`ent: missing required field "BenefitPlan.employee_deduction"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BenefitPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BenefitPlan.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "BenefitPlan.tenant"`)}
	}
	return nil
}

func (_c *BenefitPlanCreate) sqlSave(ctx context.Context) (*BenefitPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BenefitPlanCreate) createSpec() (*BenefitPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &BenefitPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(benefitplan.Table, sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(benefitplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(benefitplan.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(benefitplan.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(benefitplan.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EmployerContribution(); ok {
		_spec.SetField(benefitplan.FieldEmployerContribution, field.TypeFloat64, value)
		_node.EmployerContribution = value
	}
	if value, ok := _c.mutation.EmployeeDeduction(); ok {
		_spec.SetField(benefitplan.FieldEmployeeDeduction, field.TypeFloat64, value)
		_node.EmployeeDeduction = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(benefitplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitplan.TenantTable,
			Columns: []string{benefitplan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_benefit_plans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BenefitPlanCreateBulk is the builder for creating many BenefitPlan entities in bulk.
type BenefitPlanCreateBulk struct {
	config
	err      error
	builders []*BenefitPlanCreate
}

// Save creates the BenefitPlan entities in the database.
func (_c *BenefitPlanCreateBulk) Save(ctx context.Context) ([]*BenefitPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BenefitPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BenefitPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BenefitPlanCreateBulk) SaveX(ctx context.Context) []*BenefitPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
