// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/benefitenrollment"
	"sent/ent/benefitplan"
	"sent/ent/predicate"
	"sent/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BenefitPlanUpdate is the builder for updating BenefitPlan entities.
type BenefitPlanUpdate struct {
	config
	hooks     []Hook
	mutation  *BenefitPlanMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BenefitPlanUpdate builder.
func (_u *BenefitPlanUpdate) Where(ps ...predicate.BenefitPlan) *BenefitPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BenefitPlanUpdate) SetName(v string) *BenefitPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BenefitPlanUpdate) SetNillableName(v *string) *BenefitPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BenefitPlanUpdate) SetDescription(v string) *BenefitPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BenefitPlanUpdate) SetNillableDescription(v *string) *BenefitPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BenefitPlanUpdate) ClearDescription() *BenefitPlanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetType sets the "type" field.
func (_u *BenefitPlanUpdate) SetType(v benefitplan.Type) *BenefitPlanUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *BenefitPlanUpdate) SetNillableType(v *benefitplan.Type) *BenefitPlanUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BenefitPlanUpdate) SetStatus(v benefitplan.Status) *BenefitPlanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BenefitPlanUpdate) SetNillableStatus(v *benefitplan.Status) *BenefitPlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEmployerContribution sets the "employer_contribution" field.
func (_u *BenefitPlanUpdate) SetEmployerContribution(v float64) *BenefitPlanUpdate {
	_u.mutation.ResetEmployerContribution()
	_u.mutation.SetEmployerContribution(v)
	return _u
}

// SetNillableEmployerContribution sets the "employer_contribution" field if the given value is not nil.
func (_u *BenefitPlanUpdate) SetNillableEmployerContribution(v *float64) *BenefitPlanUpdate {
	if v != nil {
		_u.SetEmployerContribution(*v)
	}
	return _u
}

// AddEmployerContribution adds value to the "employer_contribution" field.
func (_u *BenefitPlanUpdate) AddEmployerContribution(v float64) *BenefitPlanUpdate {
	_u.mutation.AddEmployerContribution(v)
	return _u
}

// SetEmployeeDeduction sets the "employee_deduction" field.
func (_u *BenefitPlanUpdate) SetEmployeeDeduction(v float64) *BenefitPlanUpdate {
	_u.mutation.ResetEmployeeDeduction()
	_u.mutation.SetEmployeeDeduction(v)
	return _u
}

// SetNillableEmployeeDeduction sets the "employee_deduction" field if the given value is not nil.
func (_u *BenefitPlanUpdate) SetNillableEmployeeDeduction(v *float64) *BenefitPlanUpdate {
	if v != nil {
		_u.SetEmployeeDeduction(*v)
	}
	return _u
}

// AddEmployeeDeduction adds value to the "employee_deduction" field.
func (_u *BenefitPlanUpdate) AddEmployeeDeduction(v float64) *BenefitPlanUpdate {
	_u.mutation.AddEmployeeDeduction(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitPlanUpdate) SetUpdatedAt(v time.Time) *BenefitPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *BenefitPlanUpdate) SetTenantID(id int) *BenefitPlanUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *BenefitPlanUpdate) SetTenant(v *Tenant) *BenefitPlanUpdate {
	return _u.SetTenantID(v.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the BenefitEnrollment entity by IDs.
func (_u *BenefitPlanUpdate) AddEnrollmentIDs(ids ...int) *BenefitPlanUpdate {
	_u.mutation.AddEnrollmentIDs(ids...)
	return _u
}

// AddEnrollments adds the "enrollments" edges to the BenefitEnrollment entity.
func (_u *BenefitPlanUpdate) AddEnrollments(v ...*BenefitEnrollment) *BenefitPlanUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollmentIDs(ids...)
}

// Mutation returns the BenefitPlanMutation object of the builder.
func (_u *BenefitPlanUpdate) Mutation() *BenefitPlanMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *BenefitPlanUpdate) ClearTenant() *BenefitPlanUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearEnrollments clears all "enrollments" edges to the BenefitEnrollment entity.
func (_u *BenefitPlanUpdate) ClearEnrollments() *BenefitPlanUpdate {
	_u.mutation.ClearEnrollments()
	return _u
}

// RemoveEnrollmentIDs removes the "enrollments" edge to BenefitEnrollment entities by IDs.
func (_u *BenefitPlanUpdate) RemoveEnrollmentIDs(ids ...int) *BenefitPlanUpdate {
	_u.mutation.RemoveEnrollmentIDs(ids...)
	return _u
}

// RemoveEnrollments removes "enrollments" edges to BenefitEnrollment entities.
func (_u *BenefitPlanUpdate) RemoveEnrollments(v ...*BenefitEnrollment) *BenefitPlanUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BenefitPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BenefitPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := benefitplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitPlanUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := benefitplan.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BenefitPlan.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := benefitplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitPlan.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitPlan.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BenefitPlanUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BenefitPlanUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BenefitPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitplan.Table, benefitplan.Columns, sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(benefitplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(benefitplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(benefitplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(benefitplan.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(benefitplan.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EmployerContribution(); ok {
		_spec.SetField(benefitplan.FieldEmployerContribution, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployerContribution(); ok {
		_spec.AddField(benefitplan.FieldEmployerContribution, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EmployeeDeduction(); ok {
		_spec.SetField(benefitplan.FieldEmployeeDeduction, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployeeDeduction(); ok {
		_spec.AddField(benefitplan.FieldEmployeeDeduction, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitplan.TenantTable,
			Columns: []string{benefitplan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitplan.TenantTable,
			Columns: []string{benefitplan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !_u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BenefitPlanUpdateOne is the builder for updating a single BenefitPlan entity.
type BenefitPlanUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BenefitPlanMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *BenefitPlanUpdateOne) SetName(v string) *BenefitPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BenefitPlanUpdateOne) SetNillableName(v *string) *BenefitPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BenefitPlanUpdateOne) SetDescription(v string) *BenefitPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BenefitPlanUpdateOne) SetNillableDescription(v *string) *BenefitPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BenefitPlanUpdateOne) ClearDescription() *BenefitPlanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetType sets the "type" field.
func (_u *BenefitPlanUpdateOne) SetType(v benefitplan.Type) *BenefitPlanUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *BenefitPlanUpdateOne) SetNillableType(v *benefitplan.Type) *BenefitPlanUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BenefitPlanUpdateOne) SetStatus(v benefitplan.Status) *BenefitPlanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BenefitPlanUpdateOne) SetNillableStatus(v *benefitplan.Status) *BenefitPlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEmployerContribution sets the "employer_contribution" field.
func (_u *BenefitPlanUpdateOne) SetEmployerContribution(v float64) *BenefitPlanUpdateOne {
	_u.mutation.ResetEmployerContribution()
	_u.mutation.SetEmployerContribution(v)
	return _u
}

// SetNillableEmployerContribution sets the "employer_contribution" field if the given value is not nil.
func (_u *BenefitPlanUpdateOne) SetNillableEmployerContribution(v *float64) *BenefitPlanUpdateOne {
	if v != nil {
		_u.SetEmployerContribution(*v)
	}
	return _u
}

// AddEmployerContribution adds value to the "employer_contribution" field.
func (_u *BenefitPlanUpdateOne) AddEmployerContribution(v float64) *BenefitPlanUpdateOne {
	_u.mutation.AddEmployerContribution(v)
	return _u
}

// SetEmployeeDeduction sets the "employee_deduction" field.
func (_u *BenefitPlanUpdateOne) SetEmployeeDeduction(v float64) *BenefitPlanUpdateOne {
	_u.mutation.ResetEmployeeDeduction()
	_u.mutation.SetEmployeeDeduction(v)
	return _u
}

// SetNillableEmployeeDeduction sets the "employee_deduction" field if the given value is not nil.
func (_u *BenefitPlanUpdateOne) SetNillableEmployeeDeduction(v *float64) *BenefitPlanUpdateOne {
	if v != nil {
		_u.SetEmployeeDeduction(*v)
	}
	return _u
}

// AddEmployeeDeduction adds value to the "employee_deduction" field.
func (_u *BenefitPlanUpdateOne) AddEmployeeDeduction(v float64) *BenefitPlanUpdateOne {
	_u.mutation.AddEmployeeDeduction(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitPlanUpdateOne) SetUpdatedAt(v time.Time) *BenefitPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *BenefitPlanUpdateOne) SetTenantID(id int) *BenefitPlanUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *BenefitPlanUpdateOne) SetTenant(v *Tenant) *BenefitPlanUpdateOne {
	return _u.SetTenantID(v.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the BenefitEnrollment entity by IDs.
func (_u *BenefitPlanUpdateOne) AddEnrollmentIDs(ids ...int) *BenefitPlanUpdateOne {
	_u.mutation.AddEnrollmentIDs(ids...)
	return _u
}

// AddEnrollments adds the "enrollments" edges to the BenefitEnrollment entity.
func (_u *BenefitPlanUpdateOne) AddEnrollments(v ...*BenefitEnrollment) *BenefitPlanUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollmentIDs(ids...)
}

// Mutation returns the BenefitPlanMutation object of the builder.
func (_u *BenefitPlanUpdateOne) Mutation() *BenefitPlanMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *BenefitPlanUpdateOne) ClearTenant() *BenefitPlanUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearEnrollments clears all "enrollments" edges to the BenefitEnrollment entity.
func (_u *BenefitPlanUpdateOne) ClearEnrollments() *BenefitPlanUpdateOne {
	_u.mutation.ClearEnrollments()
	return _u
}

// RemoveEnrollmentIDs removes the "enrollments" edge to BenefitEnrollment entities by IDs.
func (_u *BenefitPlanUpdateOne) RemoveEnrollmentIDs(ids ...int) *BenefitPlanUpdateOne {
	_u.mutation.RemoveEnrollmentIDs(ids...)
	return _u
}

// RemoveEnrollments removes "enrollments" edges to BenefitEnrollment entities.
func (_u *BenefitPlanUpdateOne) RemoveEnrollments(v ...*BenefitEnrollment) *BenefitPlanUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollmentIDs(ids...)
}

// Where appends a list predicates to the BenefitPlanUpdate builder.
func (_u *BenefitPlanUpdateOne) Where(ps ...predicate.BenefitPlan) *BenefitPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BenefitPlanUpdateOne) Select(field string, fields ...string) *BenefitPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BenefitPlan entity.
func (_u *BenefitPlanUpdateOne) Save(ctx context.Context) (*BenefitPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitPlanUpdateOne) SaveX(ctx context.Context) *BenefitPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BenefitPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := benefitplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitPlanUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := benefitplan.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BenefitPlan.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := benefitplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitPlan.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitPlan.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BenefitPlanUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BenefitPlanUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BenefitPlanUpdateOne) sqlSave(ctx context.Context) (_node *BenefitPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitplan.Table, benefitplan.Columns, sqlgraph.NewFieldSpec(benefitplan.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BenefitPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitplan.FieldID)
		for _, f := range fields {
			if !benefitplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefitplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(benefitplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(benefitplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(benefitplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(benefitplan.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(benefitplan.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EmployerContribution(); ok {
		_spec.SetField(benefitplan.FieldEmployerContribution, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployerContribution(); ok {
		_spec.AddField(benefitplan.FieldEmployerContribution, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EmployeeDeduction(); ok {
		_spec.SetField(benefitplan.FieldEmployeeDeduction, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEmployeeDeduction(); ok {
		_spec.AddField(benefitplan.FieldEmployeeDeduction, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitplan.TenantTable,
			Columns: []string{benefitplan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitplan.TenantTable,
			Columns: []string{benefitplan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !_u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitplan.EnrollmentsTable,
			Columns: []string{benefitplan.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitenrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BenefitPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
