// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sent/ent/inventorycount"
	"sent/ent/product"
	"sent/ent/tenant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

// InventoryCount is the model entity for the InventoryCount schema.
type InventoryCount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CountedQty holds the value of the "counted_qty" field.
	CountedQty decimal.Decimal `json:"counted_qty,omitempty"`
	// SystemQty holds the value of the "system_qty" field.
	SystemQty decimal.Decimal `json:"system_qty,omitempty"`
	// Variance holds the value of the "variance" field.
	Variance decimal.Decimal `json:"variance,omitempty"`
	// CountedAt holds the value of the "counted_at" field.
	CountedAt time.Time `json:"counted_at,omitempty"`
	// CountedBy holds the value of the "counted_by" field.
	CountedBy string `json:"counted_by,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InventoryCountQuery when eager-loading is set.
	Edges                    InventoryCountEdges `json:"edges"`
	product_inventory_counts *int
	tenant_inventory_counts  *int
	selectValues             sql.SelectValues
}

// InventoryCountEdges holds the relations/edges for other nodes in the graph.
type InventoryCountEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InventoryCountEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InventoryCountEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InventoryCount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inventorycount.FieldCountedQty, inventorycount.FieldSystemQty, inventorycount.FieldVariance:
			values[i] = new(decimal.Decimal)
		case inventorycount.FieldID:
			values[i] = new(sql.NullInt64)
		case inventorycount.FieldCountedBy, inventorycount.FieldNotes:
			values[i] = new(sql.NullString)
		case inventorycount.FieldCountedAt:
			values[i] = new(sql.NullTime)
		case inventorycount.ForeignKeys[0]: // product_inventory_counts
			values[i] = new(sql.NullInt64)
		case inventorycount.ForeignKeys[1]: // tenant_inventory_counts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InventoryCount fields.
func (_m *InventoryCount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inventorycount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case inventorycount.FieldCountedQty:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field counted_qty", values[i])
			} else if value != nil {
				_m.CountedQty = *value
			}
		case inventorycount.FieldSystemQty:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field system_qty", values[i])
			} else if value != nil {
				_m.SystemQty = *value
			}
		case inventorycount.FieldVariance:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field variance", values[i])
			} else if value != nil {
				_m.Variance = *value
			}
		case inventorycount.FieldCountedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field counted_at", values[i])
			} else if value.Valid {
				_m.CountedAt = value.Time
			}
		case inventorycount.FieldCountedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field counted_by", values[i])
			} else if value.Valid {
				_m.CountedBy = value.String
			}
		case inventorycount.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case inventorycount.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field product_inventory_counts", value)
			} else if value.Valid {
				_m.product_inventory_counts = new(int)
				*_m.product_inventory_counts = int(value.Int64)
			}
		case inventorycount.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_inventory_counts", value)
			} else if value.Valid {
				_m.tenant_inventory_counts = new(int)
				*_m.tenant_inventory_counts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InventoryCount.
// This includes values selected through modifiers, order, etc.
func (_m *InventoryCount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the InventoryCount entity.
func (_m *InventoryCount) QueryTenant() *TenantQuery {
	return NewInventoryCountClient(_m.config).QueryTenant(_m)
}

// QueryProduct queries the "product" edge of the InventoryCount entity.
func (_m *InventoryCount) QueryProduct() *ProductQuery {
	return NewInventoryCountClient(_m.config).QueryProduct(_m)
}

// Update returns a builder for updating this InventoryCount.
// Note that you need to call InventoryCount.Unwrap() before calling this method if this InventoryCount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InventoryCount) Update() *InventoryCountUpdateOne {
	return NewInventoryCountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InventoryCount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InventoryCount) Unwrap() *InventoryCount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InventoryCount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InventoryCount) String() string {
	var builder strings.Builder
	builder.WriteString("InventoryCount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("counted_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.CountedQty))
	builder.WriteString(", ")
	builder.WriteString("system_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemQty))
	builder.WriteString(", ")
	builder.WriteString("variance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Variance))
	builder.WriteString(", ")
	builder.WriteString("counted_at=")
	builder.WriteString(_m.CountedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("counted_by=")
	builder.WriteString(_m.CountedBy)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// InventoryCounts is a parsable slice of InventoryCount.
type InventoryCounts []*InventoryCount
