// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sent/ent/inventoryreservation"
	"sent/ent/product"
	"sent/ent/tenant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InventoryReservation is the model entity for the InventoryReservation schema.
type InventoryReservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Status holds the value of the "status" field.
	Status inventoryreservation.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InventoryReservationQuery when eager-loading is set.
	Edges                         InventoryReservationEdges `json:"edges"`
	product_reservations          *int
	tenant_inventory_reservations *int
	selectValues                  sql.SelectValues
}

// InventoryReservationEdges holds the relations/edges for other nodes in the graph.
type InventoryReservationEdges struct {
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InventoryReservationEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InventoryReservationEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InventoryReservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inventoryreservation.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case inventoryreservation.FieldID:
			values[i] = new(sql.NullInt64)
		case inventoryreservation.FieldStatus:
			values[i] = new(sql.NullString)
		case inventoryreservation.FieldExpiresAt, inventoryreservation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case inventoryreservation.ForeignKeys[0]: // product_reservations
			values[i] = new(sql.NullInt64)
		case inventoryreservation.ForeignKeys[1]: // tenant_inventory_reservations
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InventoryReservation fields.
func (_m *InventoryReservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inventoryreservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case inventoryreservation.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case inventoryreservation.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case inventoryreservation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = inventoryreservation.Status(value.String)
			}
		case inventoryreservation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case inventoryreservation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field product_reservations", value)
			} else if value.Valid {
				_m.product_reservations = new(int)
				*_m.product_reservations = int(value.Int64)
			}
		case inventoryreservation.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_inventory_reservations", value)
			} else if value.Valid {
				_m.tenant_inventory_reservations = new(int)
				*_m.tenant_inventory_reservations = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InventoryReservation.
// This includes values selected through modifiers, order, etc.
func (_m *InventoryReservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the InventoryReservation entity.
func (_m *InventoryReservation) QueryProduct() *ProductQuery {
	return NewInventoryReservationClient(_m.config).QueryProduct(_m)
}

// QueryTenant queries the "tenant" edge of the InventoryReservation entity.
func (_m *InventoryReservation) QueryTenant() *TenantQuery {
	return NewInventoryReservationClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this InventoryReservation.
// Note that you need to call InventoryReservation.Unwrap() before calling this method if this InventoryReservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InventoryReservation) Update() *InventoryReservationUpdateOne {
	return NewInventoryReservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InventoryReservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InventoryReservation) Unwrap() *InventoryReservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InventoryReservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InventoryReservation) String() string {
	var builder strings.Builder
	builder.WriteString("InventoryReservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InventoryReservations is a parsable slice of InventoryReservation.
type InventoryReservations []*InventoryReservation
