// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sent/ent/networkdevice"
	"sent/ent/networkport"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// NetworkPort is the model entity for the NetworkPort schema.
type NetworkPort struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Vlan holds the value of the "vlan" field.
	Vlan int `json:"vlan,omitempty"`
	// MACAddress holds the value of the "mac_address" field.
	MACAddress string `json:"mac_address,omitempty"`
	// PoeEnabled holds the value of the "poe_enabled" field.
	PoeEnabled bool `json:"poe_enabled,omitempty"`
	// PoeWattage holds the value of the "poe_wattage" field.
	PoeWattage float64 `json:"poe_wattage,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NetworkPortQuery when eager-loading is set.
	Edges                NetworkPortEdges `json:"edges"`
	network_device_ports *int
	selectValues         sql.SelectValues
}

// NetworkPortEdges holds the relations/edges for other nodes in the graph.
type NetworkPortEdges struct {
	// Device holds the value of the device edge.
	Device *NetworkDevice `json:"device,omitempty"`
	// ConnectedTo holds the value of the connected_to edge.
	ConnectedTo []*NetworkLink `json:"connected_to,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NetworkPortEdges) DeviceOrErr() (*NetworkDevice, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: networkdevice.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// ConnectedToOrErr returns the ConnectedTo value or an error if the edge
// was not loaded in eager-loading.
func (e NetworkPortEdges) ConnectedToOrErr() ([]*NetworkLink, error) {
	if e.loadedTypes[1] {
		return e.ConnectedTo, nil
	}
	return nil, &NotLoadedError{edge: "connected_to"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NetworkPort) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case networkport.FieldPoeEnabled:
			values[i] = new(sql.NullBool)
		case networkport.FieldPoeWattage:
			values[i] = new(sql.NullFloat64)
		case networkport.FieldID, networkport.FieldVlan:
			values[i] = new(sql.NullInt64)
		case networkport.FieldName, networkport.FieldType, networkport.FieldStatus, networkport.FieldMACAddress, networkport.FieldDescription:
			values[i] = new(sql.NullString)
		case networkport.ForeignKeys[0]: // network_device_ports
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NetworkPort fields.
func (_m *NetworkPort) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case networkport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case networkport.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case networkport.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case networkport.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case networkport.FieldVlan:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vlan", values[i])
			} else if value.Valid {
				_m.Vlan = int(value.Int64)
			}
		case networkport.FieldMACAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mac_address", values[i])
			} else if value.Valid {
				_m.MACAddress = value.String
			}
		case networkport.FieldPoeEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field poe_enabled", values[i])
			} else if value.Valid {
				_m.PoeEnabled = value.Bool
			}
		case networkport.FieldPoeWattage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field poe_wattage", values[i])
			} else if value.Valid {
				_m.PoeWattage = value.Float64
			}
		case networkport.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case networkport.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field network_device_ports", value)
			} else if value.Valid {
				_m.network_device_ports = new(int)
				*_m.network_device_ports = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NetworkPort.
// This includes values selected through modifiers, order, etc.
func (_m *NetworkPort) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDevice queries the "device" edge of the NetworkPort entity.
func (_m *NetworkPort) QueryDevice() *NetworkDeviceQuery {
	return NewNetworkPortClient(_m.config).QueryDevice(_m)
}

// QueryConnectedTo queries the "connected_to" edge of the NetworkPort entity.
func (_m *NetworkPort) QueryConnectedTo() *NetworkLinkQuery {
	return NewNetworkPortClient(_m.config).QueryConnectedTo(_m)
}

// Update returns a builder for updating this NetworkPort.
// Note that you need to call NetworkPort.Unwrap() before calling this method if this NetworkPort
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NetworkPort) Update() *NetworkPortUpdateOne {
	return NewNetworkPortClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NetworkPort entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NetworkPort) Unwrap() *NetworkPort {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NetworkPort is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NetworkPort) String() string {
	var builder strings.Builder
	builder.WriteString("NetworkPort(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("vlan=")
	builder.WriteString(fmt.Sprintf("%v", _m.Vlan))
	builder.WriteString(", ")
	builder.WriteString("mac_address=")
	builder.WriteString(_m.MACAddress)
	builder.WriteString(", ")
	builder.WriteString("poe_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PoeEnabled))
	builder.WriteString(", ")
	builder.WriteString("poe_wattage=")
	builder.WriteString(fmt.Sprintf("%v", _m.PoeWattage))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// NetworkPorts is a parsable slice of NetworkPort.
type NetworkPorts []*NetworkPort
