// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/networkbackup"
	"sent/ent/networkdevice"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NetworkBackupCreate is the builder for creating a NetworkBackup entity.
type NetworkBackupCreate struct {
	config
	mutation *NetworkBackupMutation
	hooks    []Hook
}

// SetContentHash sets the "content_hash" field.
func (_c *NetworkBackupCreate) SetContentHash(v string) *NetworkBackupCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetVaultPath sets the "vault_path" field.
func (_c *NetworkBackupCreate) SetVaultPath(v string) *NetworkBackupCreate {
	_c.mutation.SetVaultPath(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NetworkBackupCreate) SetCreatedAt(v time.Time) *NetworkBackupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NetworkBackupCreate) SetNillableCreatedAt(v *time.Time) *NetworkBackupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDeviceID sets the "device" edge to the NetworkDevice entity by ID.
func (_c *NetworkBackupCreate) SetDeviceID(id int) *NetworkBackupCreate {
	_c.mutation.SetDeviceID(id)
	return _c
}

// SetDevice sets the "device" edge to the NetworkDevice entity.
func (_c *NetworkBackupCreate) SetDevice(v *NetworkDevice) *NetworkBackupCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the NetworkBackupMutation object of the builder.
func (_c *NetworkBackupCreate) Mutation() *NetworkBackupMutation {
	return _c.mutation
}

// Save creates the NetworkBackup in the database.
func (_c *NetworkBackupCreate) Save(ctx context.Context) (*NetworkBackup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NetworkBackupCreate) SaveX(ctx context.Context) *NetworkBackup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NetworkBackupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NetworkBackupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NetworkBackupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := networkbackup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NetworkBackupCreate) check() error {
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "NetworkBackup.content_hash"`)}
	}
	if _, ok := _c.mutation.VaultPath(); !ok {
		return &ValidationError{Name: "vault_path", err: errors.New(`ent: missing required field "NetworkBackup.vault_path"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NetworkBackup.created_at"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "NetworkBackup.device"`)}
	}
	return nil
}

func (_c *NetworkBackupCreate) sqlSave(ctx context.Context) (*NetworkBackup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NetworkBackupCreate) createSpec() (*NetworkBackup, *sqlgraph.CreateSpec) {
	var (
		_node = &NetworkBackup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(networkbackup.Table, sqlgraph.NewFieldSpec(networkbackup.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(networkbackup.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.VaultPath(); ok {
		_spec.SetField(networkbackup.FieldVaultPath, field.TypeString, value)
		_node.VaultPath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(networkbackup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkbackup.DeviceTable,
			Columns: []string{networkbackup.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.network_device_backups = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NetworkBackupCreateBulk is the builder for creating many NetworkBackup entities in bulk.
type NetworkBackupCreateBulk struct {
	config
	err      error
	builders []*NetworkBackupCreate
}

// Save creates the NetworkBackup entities in the database.
func (_c *NetworkBackupCreateBulk) Save(ctx context.Context) ([]*NetworkBackup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NetworkBackup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NetworkBackupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NetworkBackupCreateBulk) SaveX(ctx context.Context) []*NetworkBackup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NetworkBackupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NetworkBackupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
