// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sent/ent/saasidentity"
	"sent/ent/saasusage"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SaaSUsage is the model entity for the SaaSUsage schema.
type SaaSUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// FeatureName holds the value of the "feature_name" field.
	FeatureName string `json:"feature_name,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SaaSUsageQuery when eager-loading is set.
	Edges                SaaSUsageEdges `json:"edges"`
	saa_sidentity_usages *int
	selectValues         sql.SelectValues
}

// SaaSUsageEdges holds the relations/edges for other nodes in the graph.
type SaaSUsageEdges struct {
	// Identity holds the value of the identity edge.
	Identity *SaaSIdentity `json:"identity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// IdentityOrErr returns the Identity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SaaSUsageEdges) IdentityOrErr() (*SaaSIdentity, error) {
	if e.Identity != nil {
		return e.Identity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: saasidentity.Label}
	}
	return nil, &NotLoadedError{edge: "identity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SaaSUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case saasusage.FieldMetadata:
			values[i] = new([]byte)
		case saasusage.FieldID, saasusage.FieldCount:
			values[i] = new(sql.NullInt64)
		case saasusage.FieldFeatureName:
			values[i] = new(sql.NullString)
		case saasusage.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case saasusage.ForeignKeys[0]: // saa_sidentity_usages
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SaaSUsage fields.
func (_m *SaaSUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case saasusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case saasusage.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case saasusage.FieldFeatureName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature_name", values[i])
			} else if value.Valid {
				_m.FeatureName = value.String
			}
		case saasusage.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case saasusage.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case saasusage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field saa_sidentity_usages", value)
			} else if value.Valid {
				_m.saa_sidentity_usages = new(int)
				*_m.saa_sidentity_usages = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SaaSUsage.
// This includes values selected through modifiers, order, etc.
func (_m *SaaSUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIdentity queries the "identity" edge of the SaaSUsage entity.
func (_m *SaaSUsage) QueryIdentity() *SaaSIdentityQuery {
	return NewSaaSUsageClient(_m.config).QueryIdentity(_m)
}

// Update returns a builder for updating this SaaSUsage.
// Note that you need to call SaaSUsage.Unwrap() before calling this method if this SaaSUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SaaSUsage) Update() *SaaSUsageUpdateOne {
	return NewSaaSUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SaaSUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SaaSUsage) Unwrap() *SaaSUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SaaSUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SaaSUsage) String() string {
	var builder strings.Builder
	builder.WriteString("SaaSUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("feature_name=")
	builder.WriteString(_m.FeatureName)
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// SaaSUsages is a parsable slice of SaaSUsage.
type SaaSUsages []*SaaSUsage
