// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sent/ent/stockauditlog"
	"sent/ent/tenant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StockAuditLog is the model entity for the StockAuditLog schema.
type StockAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// EntityType holds the value of the "entity_type" field.
	EntityType string `json:"entity_type,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID int `json:"entity_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// Details holds the value of the "details" field.
	Details map[string]interface{} `json:"details,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StockAuditLogQuery when eager-loading is set.
	Edges                   StockAuditLogEdges `json:"edges"`
	tenant_stock_audit_logs *int
	selectValues            sql.SelectValues
}

// StockAuditLogEdges holds the relations/edges for other nodes in the graph.
type StockAuditLogEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockAuditLogEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockauditlog.FieldDetails:
			values[i] = new([]byte)
		case stockauditlog.FieldID, stockauditlog.FieldEntityID, stockauditlog.FieldUserID:
			values[i] = new(sql.NullInt64)
		case stockauditlog.FieldAction, stockauditlog.FieldEntityType, stockauditlog.FieldUserName:
			values[i] = new(sql.NullString)
		case stockauditlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case stockauditlog.ForeignKeys[0]: // tenant_stock_audit_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockAuditLog fields.
func (_m *StockAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case stockauditlog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case stockauditlog.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				_m.EntityType = value.String
			}
		case stockauditlog.FieldEntityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				_m.EntityID = int(value.Int64)
			}
		case stockauditlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case stockauditlog.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case stockauditlog.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		case stockauditlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case stockauditlog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_stock_audit_logs", value)
			} else if value.Valid {
				_m.tenant_stock_audit_logs = new(int)
				*_m.tenant_stock_audit_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StockAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *StockAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the StockAuditLog entity.
func (_m *StockAuditLog) QueryTenant() *TenantQuery {
	return NewStockAuditLogClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this StockAuditLog.
// Note that you need to call StockAuditLog.Unwrap() before calling this method if this StockAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StockAuditLog) Update() *StockAuditLogUpdateOne {
	return NewStockAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StockAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StockAuditLog) Unwrap() *StockAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StockAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("StockAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(_m.EntityType)
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", _m.Details))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StockAuditLogs is a parsable slice of StockAuditLog.
type StockAuditLogs []*StockAuditLog
