// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sent/ent/product"
	"sent/ent/stockalert"
	"sent/ent/tenant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StockAlert is the model entity for the StockAlert schema.
type StockAlert struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AlertType holds the value of the "alert_type" field.
	AlertType stockalert.AlertType `json:"alert_type,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// IsRead holds the value of the "is_read" field.
	IsRead bool `json:"is_read,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StockAlertQuery when eager-loading is set.
	Edges               StockAlertEdges `json:"edges"`
	product_alerts      *int
	tenant_stock_alerts *int
	selectValues        sql.SelectValues
}

// StockAlertEdges holds the relations/edges for other nodes in the graph.
type StockAlertEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockAlertEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockAlertEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockAlert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockalert.FieldIsRead:
			values[i] = new(sql.NullBool)
		case stockalert.FieldID:
			values[i] = new(sql.NullInt64)
		case stockalert.FieldAlertType, stockalert.FieldMessage:
			values[i] = new(sql.NullString)
		case stockalert.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case stockalert.ForeignKeys[0]: // product_alerts
			values[i] = new(sql.NullInt64)
		case stockalert.ForeignKeys[1]: // tenant_stock_alerts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockAlert fields.
func (_m *StockAlert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockalert.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case stockalert.FieldAlertType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alert_type", values[i])
			} else if value.Valid {
				_m.AlertType = stockalert.AlertType(value.String)
			}
		case stockalert.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case stockalert.FieldIsRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_read", values[i])
			} else if value.Valid {
				_m.IsRead = value.Bool
			}
		case stockalert.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case stockalert.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field product_alerts", value)
			} else if value.Valid {
				_m.product_alerts = new(int)
				*_m.product_alerts = int(value.Int64)
			}
		case stockalert.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_stock_alerts", value)
			} else if value.Valid {
				_m.tenant_stock_alerts = new(int)
				*_m.tenant_stock_alerts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StockAlert.
// This includes values selected through modifiers, order, etc.
func (_m *StockAlert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the StockAlert entity.
func (_m *StockAlert) QueryTenant() *TenantQuery {
	return NewStockAlertClient(_m.config).QueryTenant(_m)
}

// QueryProduct queries the "product" edge of the StockAlert entity.
func (_m *StockAlert) QueryProduct() *ProductQuery {
	return NewStockAlertClient(_m.config).QueryProduct(_m)
}

// Update returns a builder for updating this StockAlert.
// Note that you need to call StockAlert.Unwrap() before calling this method if this StockAlert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StockAlert) Update() *StockAlertUpdateOne {
	return NewStockAlertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StockAlert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StockAlert) Unwrap() *StockAlert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockAlert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StockAlert) String() string {
	var builder strings.Builder
	builder.WriteString("StockAlert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("alert_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.AlertType))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("is_read=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsRead))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StockAlerts is a parsable slice of StockAlert.
type StockAlerts []*StockAlert
