// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/account"
	"sent/ent/agent"
	"sent/ent/asset"
	"sent/ent/assettype"
	"sent/ent/auditlog"
	"sent/ent/budgetforecast"
	"sent/ent/calllog"
	"sent/ent/camera"
	"sent/ent/compensationagreement"
	"sent/ent/contract"
	"sent/ent/credential"
	"sent/ent/department"
	"sent/ent/detectionevent"
	"sent/ent/discoveryentry"
	"sent/ent/employee"
	"sent/ent/goal"
	"sent/ent/healthscoresnapshot"
	"sent/ent/inventoryreservation"
	"sent/ent/ivrflow"
	"sent/ent/job"
	"sent/ent/journalentry"
	"sent/ent/ledgerentry"
	"sent/ent/networkbackup"
	"sent/ent/networkdevice"
	"sent/ent/networklink"
	"sent/ent/networkport"
	"sent/ent/nexusaudit"
	"sent/ent/onetimelink"
	"sent/ent/performancereview"
	"sent/ent/permission"
	"sent/ent/product"
	"sent/ent/recording"
	"sent/ent/recurringinvoice"
	"sent/ent/reviewcycle"
	"sent/ent/saasapp"
	"sent/ent/saasfilter"
	"sent/ent/saasidentity"
	"sent/ent/saasusage"
	"sent/ent/script"
	"sent/ent/servicerate"
	"sent/ent/sop"
	"sent/ent/stockmovement"
	"sent/ent/strategicroadmap"
	"sent/ent/successionmap"
	"sent/ent/tenant"
	"sent/ent/ticket"
	"sent/ent/timeoffbalance"
	"sent/ent/timeoffpolicy"
	"sent/ent/timeoffrequest"
	"sent/ent/transaction"
	"sent/ent/user"
	"sent/ent/vaultitem"
	"sent/ent/voicemail"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// TenantCreate is the builder for creating a Tenant entity.
type TenantCreate struct {
	config
	mutation *TenantMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TenantCreate) SetName(v string) *TenantCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *TenantCreate) SetDomain(v string) *TenantCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantCreate) SetCreatedAt(v time.Time) *TenantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantCreate) SetNillableCreatedAt(v *time.Time) *TenantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *TenantCreate) SetActive(v bool) *TenantCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *TenantCreate) SetNillableActive(v *bool) *TenantCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetTransactionLimit sets the "transaction_limit" field.
func (_c *TenantCreate) SetTransactionLimit(v decimal.Decimal) *TenantCreate {
	_c.mutation.SetTransactionLimit(v)
	return _c
}

// SetNillableTransactionLimit sets the "transaction_limit" field if the given value is not nil.
func (_c *TenantCreate) SetNillableTransactionLimit(v *decimal.Decimal) *TenantCreate {
	if v != nil {
		_c.SetTransactionLimit(*v)
	}
	return _c
}

// SetParentID sets the "parent" edge to the Tenant entity by ID.
func (_c *TenantCreate) SetParentID(id int) *TenantCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Tenant entity by ID if the given value is not nil.
func (_c *TenantCreate) SetNillableParentID(id *int) *TenantCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Tenant entity.
func (_c *TenantCreate) SetParent(v *Tenant) *TenantCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Tenant entity by IDs.
func (_c *TenantCreate) AddChildIDs(ids ...int) *TenantCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Tenant entity.
func (_c *TenantCreate) AddChildren(v ...*Tenant) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *TenantCreate) AddUserIDs(ids ...int) *TenantCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *TenantCreate) AddUsers(v ...*User) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *TenantCreate) AddAccountIDs(ids ...int) *TenantCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *TenantCreate) AddAccounts(v ...*Account) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *TenantCreate) AddTransactionIDs(ids ...int) *TenantCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *TenantCreate) AddTransactions(v ...*Transaction) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the LedgerEntry entity by IDs.
func (_c *TenantCreate) AddLedgerEntryIDs(ids ...int) *TenantCreate {
	_c.mutation.AddLedgerEntryIDs(ids...)
	return _c
}

// AddLedgerEntries adds the "ledger_entries" edges to the LedgerEntry entity.
func (_c *TenantCreate) AddLedgerEntries(v ...*LedgerEntry) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLedgerEntryIDs(ids...)
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_c *TenantCreate) AddProductIDs(ids ...int) *TenantCreate {
	_c.mutation.AddProductIDs(ids...)
	return _c
}

// AddProducts adds the "products" edges to the Product entity.
func (_c *TenantCreate) AddProducts(v ...*Product) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProductIDs(ids...)
}

// AddStockMovementIDs adds the "stock_movements" edge to the StockMovement entity by IDs.
func (_c *TenantCreate) AddStockMovementIDs(ids ...int) *TenantCreate {
	_c.mutation.AddStockMovementIDs(ids...)
	return _c
}

// AddStockMovements adds the "stock_movements" edges to the StockMovement entity.
func (_c *TenantCreate) AddStockMovements(v ...*StockMovement) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStockMovementIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_c *TenantCreate) AddAuditLogIDs(ids ...int) *TenantCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_c *TenantCreate) AddAuditLogs(v ...*AuditLog) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (_c *TenantCreate) AddAgentIDs(ids ...int) *TenantCreate {
	_c.mutation.AddAgentIDs(ids...)
	return _c
}

// AddAgents adds the "agents" edges to the Agent entity.
func (_c *TenantCreate) AddAgents(v ...*Agent) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentIDs(ids...)
}

// AddDiscoveryEntryIDs adds the "discovery_entries" edge to the DiscoveryEntry entity by IDs.
func (_c *TenantCreate) AddDiscoveryEntryIDs(ids ...int) *TenantCreate {
	_c.mutation.AddDiscoveryEntryIDs(ids...)
	return _c
}

// AddDiscoveryEntries adds the "discovery_entries" edges to the DiscoveryEntry entity.
func (_c *TenantCreate) AddDiscoveryEntries(v ...*DiscoveryEntry) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDiscoveryEntryIDs(ids...)
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_c *TenantCreate) AddAssetIDs(ids ...int) *TenantCreate {
	_c.mutation.AddAssetIDs(ids...)
	return _c
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_c *TenantCreate) AddAssets(v ...*Asset) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetIDs(ids...)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_c *TenantCreate) AddCredentialIDs(ids ...int) *TenantCreate {
	_c.mutation.AddCredentialIDs(ids...)
	return _c
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_c *TenantCreate) AddCredentials(v ...*Credential) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCredentialIDs(ids...)
}

// AddOneTimeLinkIDs adds the "one_time_links" edge to the OneTimeLink entity by IDs.
func (_c *TenantCreate) AddOneTimeLinkIDs(ids ...int) *TenantCreate {
	_c.mutation.AddOneTimeLinkIDs(ids...)
	return _c
}

// AddOneTimeLinks adds the "one_time_links" edges to the OneTimeLink entity.
func (_c *TenantCreate) AddOneTimeLinks(v ...*OneTimeLink) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOneTimeLinkIDs(ids...)
}

// AddSopIDs adds the "sops" edge to the SOP entity by IDs.
func (_c *TenantCreate) AddSopIDs(ids ...int) *TenantCreate {
	_c.mutation.AddSopIDs(ids...)
	return _c
}

// AddSops adds the "sops" edges to the SOP entity.
func (_c *TenantCreate) AddSops(v ...*SOP) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSopIDs(ids...)
}

// AddCameraIDs adds the "cameras" edge to the Camera entity by IDs.
func (_c *TenantCreate) AddCameraIDs(ids ...int) *TenantCreate {
	_c.mutation.AddCameraIDs(ids...)
	return _c
}

// AddCameras adds the "cameras" edges to the Camera entity.
func (_c *TenantCreate) AddCameras(v ...*Camera) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCameraIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *TenantCreate) AddTicketIDs(ids ...int) *TenantCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *TenantCreate) AddTickets(v ...*Ticket) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// AddContractIDs adds the "contracts" edge to the Contract entity by IDs.
func (_c *TenantCreate) AddContractIDs(ids ...int) *TenantCreate {
	_c.mutation.AddContractIDs(ids...)
	return _c
}

// AddContracts adds the "contracts" edges to the Contract entity.
func (_c *TenantCreate) AddContracts(v ...*Contract) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddContractIDs(ids...)
}

// AddSaasAppIDs adds the "saas_apps" edge to the SaaSApp entity by IDs.
func (_c *TenantCreate) AddSaasAppIDs(ids ...int) *TenantCreate {
	_c.mutation.AddSaasAppIDs(ids...)
	return _c
}

// AddSaasApps adds the "saas_apps" edges to the SaaSApp entity.
func (_c *TenantCreate) AddSaasApps(v ...*SaaSApp) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSaasAppIDs(ids...)
}

// AddSaasFilterIDs adds the "saas_filters" edge to the SaaSFilter entity by IDs.
func (_c *TenantCreate) AddSaasFilterIDs(ids ...int) *TenantCreate {
	_c.mutation.AddSaasFilterIDs(ids...)
	return _c
}

// AddSaasFilters adds the "saas_filters" edges to the SaaSFilter entity.
func (_c *TenantCreate) AddSaasFilters(v ...*SaaSFilter) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSaasFilterIDs(ids...)
}

// AddCallLogIDs adds the "call_logs" edge to the CallLog entity by IDs.
func (_c *TenantCreate) AddCallLogIDs(ids ...int) *TenantCreate {
	_c.mutation.AddCallLogIDs(ids...)
	return _c
}

// AddCallLogs adds the "call_logs" edges to the CallLog entity.
func (_c *TenantCreate) AddCallLogs(v ...*CallLog) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCallLogIDs(ids...)
}

// AddIvrFlowIDs adds the "ivr_flows" edge to the IVRFlow entity by IDs.
func (_c *TenantCreate) AddIvrFlowIDs(ids ...int) *TenantCreate {
	_c.mutation.AddIvrFlowIDs(ids...)
	return _c
}

// AddIvrFlows adds the "ivr_flows" edges to the IVRFlow entity.
func (_c *TenantCreate) AddIvrFlows(v ...*IVRFlow) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIvrFlowIDs(ids...)
}

// AddVoicemailIDs adds the "voicemails" edge to the Voicemail entity by IDs.
func (_c *TenantCreate) AddVoicemailIDs(ids ...int) *TenantCreate {
	_c.mutation.AddVoicemailIDs(ids...)
	return _c
}

// AddVoicemails adds the "voicemails" edges to the Voicemail entity.
func (_c *TenantCreate) AddVoicemails(v ...*Voicemail) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoicemailIDs(ids...)
}

// AddHealthSnapshotIDs adds the "health_snapshots" edge to the HealthScoreSnapshot entity by IDs.
func (_c *TenantCreate) AddHealthSnapshotIDs(ids ...int) *TenantCreate {
	_c.mutation.AddHealthSnapshotIDs(ids...)
	return _c
}

// AddHealthSnapshots adds the "health_snapshots" edges to the HealthScoreSnapshot entity.
func (_c *TenantCreate) AddHealthSnapshots(v ...*HealthScoreSnapshot) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddHealthSnapshotIDs(ids...)
}

// AddRoadmapIDs adds the "roadmaps" edge to the StrategicRoadmap entity by IDs.
func (_c *TenantCreate) AddRoadmapIDs(ids ...int) *TenantCreate {
	_c.mutation.AddRoadmapIDs(ids...)
	return _c
}

// AddRoadmaps adds the "roadmaps" edges to the StrategicRoadmap entity.
func (_c *TenantCreate) AddRoadmaps(v ...*StrategicRoadmap) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoadmapIDs(ids...)
}

// AddServiceRateIDs adds the "service_rates" edge to the ServiceRate entity by IDs.
func (_c *TenantCreate) AddServiceRateIDs(ids ...int) *TenantCreate {
	_c.mutation.AddServiceRateIDs(ids...)
	return _c
}

// AddServiceRates adds the "service_rates" edges to the ServiceRate entity.
func (_c *TenantCreate) AddServiceRates(v ...*ServiceRate) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddServiceRateIDs(ids...)
}

// AddNetworkDeviceIDs adds the "network_devices" edge to the NetworkDevice entity by IDs.
func (_c *TenantCreate) AddNetworkDeviceIDs(ids ...int) *TenantCreate {
	_c.mutation.AddNetworkDeviceIDs(ids...)
	return _c
}

// AddNetworkDevices adds the "network_devices" edges to the NetworkDevice entity.
func (_c *TenantCreate) AddNetworkDevices(v ...*NetworkDevice) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNetworkDeviceIDs(ids...)
}

// AddNetworkBackupIDs adds the "network_backups" edge to the NetworkBackup entity by IDs.
func (_c *TenantCreate) AddNetworkBackupIDs(ids ...int) *TenantCreate {
	_c.mutation.AddNetworkBackupIDs(ids...)
	return _c
}

// AddNetworkBackups adds the "network_backups" edges to the NetworkBackup entity.
func (_c *TenantCreate) AddNetworkBackups(v ...*NetworkBackup) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNetworkBackupIDs(ids...)
}

// AddBudgetForecastIDs adds the "budget_forecasts" edge to the BudgetForecast entity by IDs.
func (_c *TenantCreate) AddBudgetForecastIDs(ids ...int) *TenantCreate {
	_c.mutation.AddBudgetForecastIDs(ids...)
	return _c
}

// AddBudgetForecasts adds the "budget_forecasts" edges to the BudgetForecast entity.
func (_c *TenantCreate) AddBudgetForecasts(v ...*BudgetForecast) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBudgetForecastIDs(ids...)
}

// AddEmployeeIDs adds the "employees" edge to the Employee entity by IDs.
func (_c *TenantCreate) AddEmployeeIDs(ids ...int) *TenantCreate {
	_c.mutation.AddEmployeeIDs(ids...)
	return _c
}

// AddEmployees adds the "employees" edges to the Employee entity.
func (_c *TenantCreate) AddEmployees(v ...*Employee) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEmployeeIDs(ids...)
}

// AddCompensationAgreementIDs adds the "compensation_agreements" edge to the CompensationAgreement entity by IDs.
func (_c *TenantCreate) AddCompensationAgreementIDs(ids ...int) *TenantCreate {
	_c.mutation.AddCompensationAgreementIDs(ids...)
	return _c
}

// AddCompensationAgreements adds the "compensation_agreements" edges to the CompensationAgreement entity.
func (_c *TenantCreate) AddCompensationAgreements(v ...*CompensationAgreement) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompensationAgreementIDs(ids...)
}

// AddVaultItemIDs adds the "vault_items" edge to the VaultItem entity by IDs.
func (_c *TenantCreate) AddVaultItemIDs(ids ...int) *TenantCreate {
	_c.mutation.AddVaultItemIDs(ids...)
	return _c
}

// AddVaultItems adds the "vault_items" edges to the VaultItem entity.
func (_c *TenantCreate) AddVaultItems(v ...*VaultItem) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVaultItemIDs(ids...)
}

// AddJournalEntryIDs adds the "journal_entries" edge to the JournalEntry entity by IDs.
func (_c *TenantCreate) AddJournalEntryIDs(ids ...int) *TenantCreate {
	_c.mutation.AddJournalEntryIDs(ids...)
	return _c
}

// AddJournalEntries adds the "journal_entries" edges to the JournalEntry entity.
func (_c *TenantCreate) AddJournalEntries(v ...*JournalEntry) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddJournalEntryIDs(ids...)
}

// AddRecurringInvoiceIDs adds the "recurring_invoices" edge to the RecurringInvoice entity by IDs.
func (_c *TenantCreate) AddRecurringInvoiceIDs(ids ...int) *TenantCreate {
	_c.mutation.AddRecurringInvoiceIDs(ids...)
	return _c
}

// AddRecurringInvoices adds the "recurring_invoices" edges to the RecurringInvoice entity.
func (_c *TenantCreate) AddRecurringInvoices(v ...*RecurringInvoice) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecurringInvoiceIDs(ids...)
}

// AddInventoryReservationIDs adds the "inventory_reservations" edge to the InventoryReservation entity by IDs.
func (_c *TenantCreate) AddInventoryReservationIDs(ids ...int) *TenantCreate {
	_c.mutation.AddInventoryReservationIDs(ids...)
	return _c
}

// AddInventoryReservations adds the "inventory_reservations" edges to the InventoryReservation entity.
func (_c *TenantCreate) AddInventoryReservations(v ...*InventoryReservation) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInventoryReservationIDs(ids...)
}

// AddDepartmentIDs adds the "departments" edge to the Department entity by IDs.
func (_c *TenantCreate) AddDepartmentIDs(ids ...int) *TenantCreate {
	_c.mutation.AddDepartmentIDs(ids...)
	return _c
}

// AddDepartments adds the "departments" edges to the Department entity.
func (_c *TenantCreate) AddDepartments(v ...*Department) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDepartmentIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_c *TenantCreate) AddPermissionIDs(ids ...int) *TenantCreate {
	_c.mutation.AddPermissionIDs(ids...)
	return _c
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_c *TenantCreate) AddPermissions(v ...*Permission) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionIDs(ids...)
}

// AddAssetTypeIDs adds the "asset_types" edge to the AssetType entity by IDs.
func (_c *TenantCreate) AddAssetTypeIDs(ids ...int) *TenantCreate {
	_c.mutation.AddAssetTypeIDs(ids...)
	return _c
}

// AddAssetTypes adds the "asset_types" edges to the AssetType entity.
func (_c *TenantCreate) AddAssetTypes(v ...*AssetType) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetTypeIDs(ids...)
}

// AddDetectionEventIDs adds the "detection_events" edge to the DetectionEvent entity by IDs.
func (_c *TenantCreate) AddDetectionEventIDs(ids ...int) *TenantCreate {
	_c.mutation.AddDetectionEventIDs(ids...)
	return _c
}

// AddDetectionEvents adds the "detection_events" edges to the DetectionEvent entity.
func (_c *TenantCreate) AddDetectionEvents(v ...*DetectionEvent) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDetectionEventIDs(ids...)
}

// AddSaasIdentityIDs adds the "saas_identities" edge to the SaaSIdentity entity by IDs.
func (_c *TenantCreate) AddSaasIdentityIDs(ids ...int) *TenantCreate {
	_c.mutation.AddSaasIdentityIDs(ids...)
	return _c
}

// AddSaasIdentities adds the "saas_identities" edges to the SaaSIdentity entity.
func (_c *TenantCreate) AddSaasIdentities(v ...*SaaSIdentity) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSaasIdentityIDs(ids...)
}

// AddSaasUsageIDs adds the "saas_usages" edge to the SaaSUsage entity by IDs.
func (_c *TenantCreate) AddSaasUsageIDs(ids ...int) *TenantCreate {
	_c.mutation.AddSaasUsageIDs(ids...)
	return _c
}

// AddSaasUsages adds the "saas_usages" edges to the SaaSUsage entity.
func (_c *TenantCreate) AddSaasUsages(v ...*SaaSUsage) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSaasUsageIDs(ids...)
}

// AddRecordingIDs adds the "recordings" edge to the Recording entity by IDs.
func (_c *TenantCreate) AddRecordingIDs(ids ...int) *TenantCreate {
	_c.mutation.AddRecordingIDs(ids...)
	return _c
}

// AddRecordings adds the "recordings" edges to the Recording entity.
func (_c *TenantCreate) AddRecordings(v ...*Recording) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordingIDs(ids...)
}

// AddNetworkLinkIDs adds the "network_links" edge to the NetworkLink entity by IDs.
func (_c *TenantCreate) AddNetworkLinkIDs(ids ...int) *TenantCreate {
	_c.mutation.AddNetworkLinkIDs(ids...)
	return _c
}

// AddNetworkLinks adds the "network_links" edges to the NetworkLink entity.
func (_c *TenantCreate) AddNetworkLinks(v ...*NetworkLink) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNetworkLinkIDs(ids...)
}

// AddNetworkPortIDs adds the "network_ports" edge to the NetworkPort entity by IDs.
func (_c *TenantCreate) AddNetworkPortIDs(ids ...int) *TenantCreate {
	_c.mutation.AddNetworkPortIDs(ids...)
	return _c
}

// AddNetworkPorts adds the "network_ports" edges to the NetworkPort entity.
func (_c *TenantCreate) AddNetworkPorts(v ...*NetworkPort) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNetworkPortIDs(ids...)
}

// AddNexusAuditIDs adds the "nexus_audits" edge to the NexusAudit entity by IDs.
func (_c *TenantCreate) AddNexusAuditIDs(ids ...int) *TenantCreate {
	_c.mutation.AddNexusAuditIDs(ids...)
	return _c
}

// AddNexusAudits adds the "nexus_audits" edges to the NexusAudit entity.
func (_c *TenantCreate) AddNexusAudits(v ...*NexusAudit) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNexusAuditIDs(ids...)
}

// AddSuccessionMapIDs adds the "succession_maps" edge to the SuccessionMap entity by IDs.
func (_c *TenantCreate) AddSuccessionMapIDs(ids ...int) *TenantCreate {
	_c.mutation.AddSuccessionMapIDs(ids...)
	return _c
}

// AddSuccessionMaps adds the "succession_maps" edges to the SuccessionMap entity.
func (_c *TenantCreate) AddSuccessionMaps(v ...*SuccessionMap) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSuccessionMapIDs(ids...)
}

// SetCustomerAccountID sets the "customer_account" edge to the Account entity by ID.
func (_c *TenantCreate) SetCustomerAccountID(id int) *TenantCreate {
	_c.mutation.SetCustomerAccountID(id)
	return _c
}

// SetNillableCustomerAccountID sets the "customer_account" edge to the Account entity by ID if the given value is not nil.
func (_c *TenantCreate) SetNillableCustomerAccountID(id *int) *TenantCreate {
	if id != nil {
		_c = _c.SetCustomerAccountID(*id)
	}
	return _c
}

// SetCustomerAccount sets the "customer_account" edge to the Account entity.
func (_c *TenantCreate) SetCustomerAccount(v *Account) *TenantCreate {
	return _c.SetCustomerAccountID(v.ID)
}

// AddScriptIDs adds the "scripts" edge to the Script entity by IDs.
func (_c *TenantCreate) AddScriptIDs(ids ...int) *TenantCreate {
	_c.mutation.AddScriptIDs(ids...)
	return _c
}

// AddScripts adds the "scripts" edges to the Script entity.
func (_c *TenantCreate) AddScripts(v ...*Script) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScriptIDs(ids...)
}

// AddJobIDs adds the "jobs" edge to the Job entity by IDs.
func (_c *TenantCreate) AddJobIDs(ids ...int) *TenantCreate {
	_c.mutation.AddJobIDs(ids...)
	return _c
}

// AddJobs adds the "jobs" edges to the Job entity.
func (_c *TenantCreate) AddJobs(v ...*Job) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddJobIDs(ids...)
}

// AddTimeOffRequestIDs adds the "time_off_requests" edge to the TimeOffRequest entity by IDs.
func (_c *TenantCreate) AddTimeOffRequestIDs(ids ...int) *TenantCreate {
	_c.mutation.AddTimeOffRequestIDs(ids...)
	return _c
}

// AddTimeOffRequests adds the "time_off_requests" edges to the TimeOffRequest entity.
func (_c *TenantCreate) AddTimeOffRequests(v ...*TimeOffRequest) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimeOffRequestIDs(ids...)
}

// AddTimeOffPolicyIDs adds the "time_off_policies" edge to the TimeOffPolicy entity by IDs.
func (_c *TenantCreate) AddTimeOffPolicyIDs(ids ...int) *TenantCreate {
	_c.mutation.AddTimeOffPolicyIDs(ids...)
	return _c
}

// AddTimeOffPolicies adds the "time_off_policies" edges to the TimeOffPolicy entity.
func (_c *TenantCreate) AddTimeOffPolicies(v ...*TimeOffPolicy) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimeOffPolicyIDs(ids...)
}

// AddTimeOffBalanceIDs adds the "time_off_balances" edge to the TimeOffBalance entity by IDs.
func (_c *TenantCreate) AddTimeOffBalanceIDs(ids ...int) *TenantCreate {
	_c.mutation.AddTimeOffBalanceIDs(ids...)
	return _c
}

// AddTimeOffBalances adds the "time_off_balances" edges to the TimeOffBalance entity.
func (_c *TenantCreate) AddTimeOffBalances(v ...*TimeOffBalance) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimeOffBalanceIDs(ids...)
}

// AddReviewCycleIDs adds the "review_cycles" edge to the ReviewCycle entity by IDs.
func (_c *TenantCreate) AddReviewCycleIDs(ids ...int) *TenantCreate {
	_c.mutation.AddReviewCycleIDs(ids...)
	return _c
}

// AddReviewCycles adds the "review_cycles" edges to the ReviewCycle entity.
func (_c *TenantCreate) AddReviewCycles(v ...*ReviewCycle) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewCycleIDs(ids...)
}

// AddPerformanceReviewIDs adds the "performance_reviews" edge to the PerformanceReview entity by IDs.
func (_c *TenantCreate) AddPerformanceReviewIDs(ids ...int) *TenantCreate {
	_c.mutation.AddPerformanceReviewIDs(ids...)
	return _c
}

// AddPerformanceReviews adds the "performance_reviews" edges to the PerformanceReview entity.
func (_c *TenantCreate) AddPerformanceReviews(v ...*PerformanceReview) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPerformanceReviewIDs(ids...)
}

// AddGoalIDs adds the "goals" edge to the Goal entity by IDs.
func (_c *TenantCreate) AddGoalIDs(ids ...int) *TenantCreate {
	_c.mutation.AddGoalIDs(ids...)
	return _c
}

// AddGoals adds the "goals" edges to the Goal entity.
func (_c *TenantCreate) AddGoals(v ...*Goal) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGoalIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_c *TenantCreate) Mutation() *TenantMutation {
	return _c.mutation
}

// Save creates the Tenant in the database.
func (_c *TenantCreate) Save(ctx context.Context) (*Tenant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantCreate) SaveX(ctx context.Context) *Tenant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := tenant.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.TransactionLimit(); !ok {
		v := tenant.DefaultTransactionLimit
		_c.mutation.SetTransactionLimit(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tenant.name"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Tenant.domain"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tenant.created_at"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Tenant.active"`)}
	}
	if _, ok := _c.mutation.TransactionLimit(); !ok {
		return &ValidationError{Name: "transaction_limit", err: errors.New(`ent: missing required field "Tenant.transaction_limit"`)}
	}
	return nil
}

func (_c *TenantCreate) sqlSave(ctx context.Context) (*Tenant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantCreate) createSpec() (*Tenant, *sqlgraph.CreateSpec) {
	var (
		_node = &Tenant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenant.Table, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(tenant.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.TransactionLimit(); ok {
		_spec.SetField(tenant.FieldTransactionLimit, field.TypeOther, value)
		_node.TransactionLimit = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenant.ParentTable,
			Columns: []string{tenant.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ChildrenTable,
			Columns: []string{tenant.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AccountsTable,
			Columns: []string{tenant.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TransactionsTable,
			Columns: []string{tenant.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LedgerEntriesTable,
			Columns: []string{tenant.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ProductsTable,
			Columns: []string{tenant.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StockMovementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.StockMovementsTable,
			Columns: []string{tenant.StockMovementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockmovement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AuditLogsTable,
			Columns: []string{tenant.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AgentsTable,
			Columns: []string{tenant.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DiscoveryEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DiscoveryEntriesTable,
			Columns: []string{tenant.DiscoveryEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discoveryentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AssetsTable,
			Columns: []string{tenant.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CredentialsTable,
			Columns: []string{tenant.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OneTimeLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.OneTimeLinksTable,
			Columns: []string{tenant.OneTimeLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(onetimelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SopsTable,
			Columns: []string{tenant.SopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CamerasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CamerasTable,
			Columns: []string{tenant.CamerasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(camera.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TicketsTable,
			Columns: []string{tenant.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContractsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ContractsTable,
			Columns: []string{tenant.ContractsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contract.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SaasAppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SaasAppsTable,
			Columns: []string{tenant.SaasAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saasapp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SaasFiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SaasFiltersTable,
			Columns: []string{tenant.SaasFiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saasfilter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CallLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CallLogsTable,
			Columns: []string{tenant.CallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IvrFlowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.IvrFlowsTable,
			Columns: []string{tenant.IvrFlowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ivrflow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VoicemailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VoicemailsTable,
			Columns: []string{tenant.VoicemailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voicemail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HealthSnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.HealthSnapshotsTable,
			Columns: []string{tenant.HealthSnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthscoresnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoadmapsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.RoadmapsTable,
			Columns: []string{tenant.RoadmapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(strategicroadmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ServiceRatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ServiceRatesTable,
			Columns: []string{tenant.ServiceRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicerate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NetworkDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NetworkDevicesTable,
			Columns: []string{tenant.NetworkDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NetworkBackupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NetworkBackupsTable,
			Columns: []string{tenant.NetworkBackupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkbackup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BudgetForecastsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BudgetForecastsTable,
			Columns: []string{tenant.BudgetForecastsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budgetforecast.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompensationAgreementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CompensationAgreementsTable,
			Columns: []string{tenant.CompensationAgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compensationagreement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VaultItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VaultItemsTable,
			Columns: []string{tenant.VaultItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.JournalEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.JournalEntriesTable,
			Columns: []string{tenant.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecurringInvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.RecurringInvoicesTable,
			Columns: []string{tenant.RecurringInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringinvoice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InventoryReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InventoryReservationsTable,
			Columns: []string{tenant.InventoryReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryreservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DepartmentsTable,
			Columns: []string{tenant.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PermissionsTable,
			Columns: []string{tenant.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AssetTypesTable,
			Columns: []string{tenant.AssetTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DetectionEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DetectionEventsTable,
			Columns: []string{tenant.DetectionEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detectionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SaasIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SaasIdentitiesTable,
			Columns: []string{tenant.SaasIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saasidentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SaasUsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SaasUsagesTable,
			Columns: []string{tenant.SaasUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saasusage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecordingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.RecordingsTable,
			Columns: []string{tenant.RecordingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recording.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NetworkLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NetworkLinksTable,
			Columns: []string{tenant.NetworkLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networklink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NetworkPortsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NetworkPortsTable,
			Columns: []string{tenant.NetworkPortsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NexusAuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NexusAuditsTable,
			Columns: []string{tenant.NexusAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nexusaudit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SuccessionMapsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SuccessionMapsTable,
			Columns: []string{tenant.SuccessionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(successionmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomerAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tenant.CustomerAccountTable,
			Columns: []string{tenant.CustomerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_customer_account = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ScriptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ScriptsTable,
			Columns: []string{tenant.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.JobsTable,
			Columns: []string{tenant.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimeOffRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TimeOffRequestsTable,
			Columns: []string{tenant.TimeOffRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeoffrequest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimeOffPoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TimeOffPoliciesTable,
			Columns: []string{tenant.TimeOffPoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeoffpolicy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimeOffBalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TimeOffBalancesTable,
			Columns: []string{tenant.TimeOffBalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeoffbalance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewCyclesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ReviewCyclesTable,
			Columns: []string{tenant.ReviewCyclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reviewcycle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PerformanceReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PerformanceReviewsTable,
			Columns: []string{tenant.PerformanceReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(performancereview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GoalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.GoalsTable,
			Columns: []string{tenant.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantCreateBulk is the builder for creating many Tenant entities in bulk.
type TenantCreateBulk struct {
	config
	err      error
	builders []*TenantCreate
}

// Save creates the Tenant entities in the database.
func (_c *TenantCreateBulk) Save(ctx context.Context) ([]*Tenant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tenant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantCreateBulk) SaveX(ctx context.Context) []*Tenant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
