// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"sent/ent/employee"
	"sent/ent/tenant"
	"sent/ent/timeoffbalance"
	"sent/ent/timeoffpolicy"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TimeOffBalance is the model entity for the TimeOffBalance schema.
type TimeOffBalance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Year holds the value of the "year" field.
	Year int `json:"year,omitempty"`
	// AvailableHours holds the value of the "available_hours" field.
	AvailableHours float64 `json:"available_hours,omitempty"`
	// UsedHours holds the value of the "used_hours" field.
	UsedHours float64 `json:"used_hours,omitempty"`
	// PendingHours holds the value of the "pending_hours" field.
	PendingHours float64 `json:"pending_hours,omitempty"`
	// AccruedHours holds the value of the "accrued_hours" field.
	AccruedHours float64 `json:"accrued_hours,omitempty"`
	// CarriedOverHours holds the value of the "carried_over_hours" field.
	CarriedOverHours float64 `json:"carried_over_hours,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TimeOffBalanceQuery when eager-loading is set.
	Edges                      TimeOffBalanceEdges `json:"edges"`
	employee_time_off_balances *int
	tenant_time_off_balances   *int
	time_off_policy_balances   *int
	selectValues               sql.SelectValues
}

// TimeOffBalanceEdges holds the relations/edges for other nodes in the graph.
type TimeOffBalanceEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Employee holds the value of the employee edge.
	Employee *Employee `json:"employee,omitempty"`
	// Policy holds the value of the policy edge.
	Policy *TimeOffPolicy `json:"policy,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimeOffBalanceEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimeOffBalanceEdges) EmployeeOrErr() (*Employee, error) {
	if e.Employee != nil {
		return e.Employee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: employee.Label}
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// PolicyOrErr returns the Policy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimeOffBalanceEdges) PolicyOrErr() (*TimeOffPolicy, error) {
	if e.Policy != nil {
		return e.Policy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: timeoffpolicy.Label}
	}
	return nil, &NotLoadedError{edge: "policy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TimeOffBalance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timeoffbalance.FieldAvailableHours, timeoffbalance.FieldUsedHours, timeoffbalance.FieldPendingHours, timeoffbalance.FieldAccruedHours, timeoffbalance.FieldCarriedOverHours:
			values[i] = new(sql.NullFloat64)
		case timeoffbalance.FieldID, timeoffbalance.FieldYear:
			values[i] = new(sql.NullInt64)
		case timeoffbalance.FieldCreatedAt, timeoffbalance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case timeoffbalance.ForeignKeys[0]: // employee_time_off_balances
			values[i] = new(sql.NullInt64)
		case timeoffbalance.ForeignKeys[1]: // tenant_time_off_balances
			values[i] = new(sql.NullInt64)
		case timeoffbalance.ForeignKeys[2]: // time_off_policy_balances
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TimeOffBalance fields.
func (_m *TimeOffBalance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timeoffbalance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case timeoffbalance.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = int(value.Int64)
			}
		case timeoffbalance.FieldAvailableHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field available_hours", values[i])
			} else if value.Valid {
				_m.AvailableHours = value.Float64
			}
		case timeoffbalance.FieldUsedHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_hours", values[i])
			} else if value.Valid {
				_m.UsedHours = value.Float64
			}
		case timeoffbalance.FieldPendingHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_hours", values[i])
			} else if value.Valid {
				_m.PendingHours = value.Float64
			}
		case timeoffbalance.FieldAccruedHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field accrued_hours", values[i])
			} else if value.Valid {
				_m.AccruedHours = value.Float64
			}
		case timeoffbalance.FieldCarriedOverHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field carried_over_hours", values[i])
			} else if value.Valid {
				_m.CarriedOverHours = value.Float64
			}
		case timeoffbalance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case timeoffbalance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case timeoffbalance.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field employee_time_off_balances", value)
			} else if value.Valid {
				_m.employee_time_off_balances = new(int)
				*_m.employee_time_off_balances = int(value.Int64)
			}
		case timeoffbalance.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_time_off_balances", value)
			} else if value.Valid {
				_m.tenant_time_off_balances = new(int)
				*_m.tenant_time_off_balances = int(value.Int64)
			}
		case timeoffbalance.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field time_off_policy_balances", value)
			} else if value.Valid {
				_m.time_off_policy_balances = new(int)
				*_m.time_off_policy_balances = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TimeOffBalance.
// This includes values selected through modifiers, order, etc.
func (_m *TimeOffBalance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the TimeOffBalance entity.
func (_m *TimeOffBalance) QueryTenant() *TenantQuery {
	return NewTimeOffBalanceClient(_m.config).QueryTenant(_m)
}

// QueryEmployee queries the "employee" edge of the TimeOffBalance entity.
func (_m *TimeOffBalance) QueryEmployee() *EmployeeQuery {
	return NewTimeOffBalanceClient(_m.config).QueryEmployee(_m)
}

// QueryPolicy queries the "policy" edge of the TimeOffBalance entity.
func (_m *TimeOffBalance) QueryPolicy() *TimeOffPolicyQuery {
	return NewTimeOffBalanceClient(_m.config).QueryPolicy(_m)
}

// Update returns a builder for updating this TimeOffBalance.
// Note that you need to call TimeOffBalance.Unwrap() before calling this method if this TimeOffBalance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TimeOffBalance) Update() *TimeOffBalanceUpdateOne {
	return NewTimeOffBalanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TimeOffBalance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TimeOffBalance) Unwrap() *TimeOffBalance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TimeOffBalance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TimeOffBalance) String() string {
	var builder strings.Builder
	builder.WriteString("TimeOffBalance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("year=")
	builder.WriteString(fmt.Sprintf("%v", _m.Year))
	builder.WriteString(", ")
	builder.WriteString("available_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableHours))
	builder.WriteString(", ")
	builder.WriteString("used_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedHours))
	builder.WriteString(", ")
	builder.WriteString("pending_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingHours))
	builder.WriteString(", ")
	builder.WriteString("accrued_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccruedHours))
	builder.WriteString(", ")
	builder.WriteString("carried_over_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarriedOverHours))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TimeOffBalances is a parsable slice of TimeOffBalance.
type TimeOffBalances []*TimeOffBalance
