// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/employee"
	"sent/ent/ticket"
	"sent/ent/timeentry"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimeEntryCreate is the builder for creating a TimeEntry entity.
type TimeEntryCreate struct {
	config
	mutation *TimeEntryMutation
	hooks    []Hook
}

// SetStartTime sets the "start_time" field.
func (_c *TimeEntryCreate) SetStartTime(v time.Time) *TimeEntryCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableStartTime(v *time.Time) *TimeEntryCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *TimeEntryCreate) SetEndTime(v time.Time) *TimeEntryCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableEndTime(v *time.Time) *TimeEntryCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TimeEntryCreate) SetCreatedAt(v time.Time) *TimeEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableCreatedAt(v *time.Time) *TimeEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTicketID sets the "ticket_id" field.
func (_c *TimeEntryCreate) SetTicketID(v int) *TimeEntryCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableTicketID(v *int) *TimeEntryCreate {
	if v != nil {
		_c.SetTicketID(*v)
	}
	return _c
}

// SetTechnicianID sets the "technician_id" field.
func (_c *TimeEntryCreate) SetTechnicianID(v int) *TimeEntryCreate {
	_c.mutation.SetTechnicianID(v)
	return _c
}

// SetNillableTechnicianID sets the "technician_id" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableTechnicianID(v *int) *TimeEntryCreate {
	if v != nil {
		_c.SetTechnicianID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TimeEntryCreate) SetStatus(v timeentry.Status) *TimeEntryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableStatus(v *timeentry.Status) *TimeEntryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWorkType sets the "work_type" field.
func (_c *TimeEntryCreate) SetWorkType(v string) *TimeEntryCreate {
	_c.mutation.SetWorkType(v)
	return _c
}

// SetNillableWorkType sets the "work_type" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableWorkType(v *string) *TimeEntryCreate {
	if v != nil {
		_c.SetWorkType(*v)
	}
	return _c
}

// SetDurationHours sets the "duration_hours" field.
func (_c *TimeEntryCreate) SetDurationHours(v float64) *TimeEntryCreate {
	_c.mutation.SetDurationHours(v)
	return _c
}

// SetNillableDurationHours sets the "duration_hours" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableDurationHours(v *float64) *TimeEntryCreate {
	if v != nil {
		_c.SetDurationHours(*v)
	}
	return _c
}

// SetInvoiceID sets the "invoice_id" field.
func (_c *TimeEntryCreate) SetInvoiceID(v int) *TimeEntryCreate {
	_c.mutation.SetInvoiceID(v)
	return _c
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_c *TimeEntryCreate) SetNillableInvoiceID(v *int) *TimeEntryCreate {
	if v != nil {
		_c.SetInvoiceID(*v)
	}
	return _c
}

// SetEmployeeID sets the "employee" edge to the Employee entity by ID.
func (_c *TimeEntryCreate) SetEmployeeID(id int) *TimeEntryCreate {
	_c.mutation.SetEmployeeID(id)
	return _c
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *TimeEntryCreate) SetEmployee(v *Employee) *TimeEntryCreate {
	return _c.SetEmployeeID(v.ID)
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_c *TimeEntryCreate) SetTicket(v *Ticket) *TimeEntryCreate {
	return _c.SetTicketID(v.ID)
}

// Mutation returns the TimeEntryMutation object of the builder.
func (_c *TimeEntryCreate) Mutation() *TimeEntryMutation {
	return _c.mutation
}

// Save creates the TimeEntry in the database.
func (_c *TimeEntryCreate) Save(ctx context.Context) (*TimeEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimeEntryCreate) SaveX(ctx context.Context) *TimeEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimeEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimeEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TimeEntryCreate) defaults() {
	if _, ok := _c.mutation.StartTime(); !ok {
		v := timeentry.DefaultStartTime()
		_c.mutation.SetStartTime(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := timeentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := timeentry.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.WorkType(); !ok {
		v := timeentry.DefaultWorkType
		_c.mutation.SetWorkType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimeEntryCreate) check() error {
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "TimeEntry.start_time"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TimeEntry.created_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TimeEntry.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := timeentry.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TimeEntry.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkType(); !ok {
		return &ValidationError{Name: "work_type", err: errors.New(`ent: missing required field "TimeEntry.work_type"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "TimeEntry.employee"`)}
	}
	return nil
}

func (_c *TimeEntryCreate) sqlSave(ctx context.Context) (*TimeEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimeEntryCreate) createSpec() (*TimeEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &TimeEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timeentry.Table, sqlgraph.NewFieldSpec(timeentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(timeentry.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(timeentry.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(timeentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.TechnicianID(); ok {
		_spec.SetField(timeentry.FieldTechnicianID, field.TypeInt, value)
		_node.TechnicianID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(timeentry.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.WorkType(); ok {
		_spec.SetField(timeentry.FieldWorkType, field.TypeString, value)
		_node.WorkType = value
	}
	if value, ok := _c.mutation.DurationHours(); ok {
		_spec.SetField(timeentry.FieldDurationHours, field.TypeFloat64, value)
		_node.DurationHours = value
	}
	if value, ok := _c.mutation.InvoiceID(); ok {
		_spec.SetField(timeentry.FieldInvoiceID, field.TypeInt, value)
		_node.InvoiceID = value
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timeentry.EmployeeTable,
			Columns: []string{timeentry.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.employee_time_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   timeentry.TicketTable,
			Columns: []string{timeentry.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TimeEntryCreateBulk is the builder for creating many TimeEntry entities in bulk.
type TimeEntryCreateBulk struct {
	config
	err      error
	builders []*TimeEntryCreate
}

// Save creates the TimeEntry entities in the database.
func (_c *TimeEntryCreateBulk) Save(ctx context.Context) ([]*TimeEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TimeEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimeEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimeEntryCreateBulk) SaveX(ctx context.Context) []*TimeEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimeEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimeEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
