// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sent/ent/tenant"
	"sent/ent/vaultitem"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// VaultItem is the model entity for the VaultItem schema.
type VaultItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// FileType holds the value of the "file_type" field.
	FileType string `json:"file_type,omitempty"`
	// Encrypted holds the value of the "encrypted" field.
	Encrypted bool `json:"encrypted,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// IsDir holds the value of the "is_dir" field.
	IsDir bool `json:"is_dir,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VaultItemQuery when eager-loading is set.
	Edges              VaultItemEdges `json:"edges"`
	tenant_vault_items *int
	selectValues       sql.SelectValues
}

// VaultItemEdges holds the relations/edges for other nodes in the graph.
type VaultItemEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// ShareLinks holds the value of the share_links edge.
	ShareLinks []*VaultShareLink `json:"share_links,omitempty"`
	// Versions holds the value of the versions edge.
	Versions []*VaultVersion `json:"versions,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*VaultComment `json:"comments,omitempty"`
	// FavoritedBy holds the value of the favorited_by edge.
	FavoritedBy []*VaultFavorite `json:"favorited_by,omitempty"`
	// LegalHolds holds the value of the legal_holds edge.
	LegalHolds []*LegalHold `json:"legal_holds,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VaultItemEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ShareLinksOrErr returns the ShareLinks value or an error if the edge
// was not loaded in eager-loading.
func (e VaultItemEdges) ShareLinksOrErr() ([]*VaultShareLink, error) {
	if e.loadedTypes[1] {
		return e.ShareLinks, nil
	}
	return nil, &NotLoadedError{edge: "share_links"}
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e VaultItemEdges) VersionsOrErr() ([]*VaultVersion, error) {
	if e.loadedTypes[2] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e VaultItemEdges) CommentsOrErr() ([]*VaultComment, error) {
	if e.loadedTypes[3] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// FavoritedByOrErr returns the FavoritedBy value or an error if the edge
// was not loaded in eager-loading.
func (e VaultItemEdges) FavoritedByOrErr() ([]*VaultFavorite, error) {
	if e.loadedTypes[4] {
		return e.FavoritedBy, nil
	}
	return nil, &NotLoadedError{edge: "favorited_by"}
}

// LegalHoldsOrErr returns the LegalHolds value or an error if the edge
// was not loaded in eager-loading.
func (e VaultItemEdges) LegalHoldsOrErr() ([]*LegalHold, error) {
	if e.loadedTypes[5] {
		return e.LegalHolds, nil
	}
	return nil, &NotLoadedError{edge: "legal_holds"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VaultItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vaultitem.FieldMetadata:
			values[i] = new([]byte)
		case vaultitem.FieldEncrypted, vaultitem.FieldIsDir:
			values[i] = new(sql.NullBool)
		case vaultitem.FieldID, vaultitem.FieldSize:
			values[i] = new(sql.NullInt64)
		case vaultitem.FieldPath, vaultitem.FieldName, vaultitem.FieldHash, vaultitem.FieldFileType, vaultitem.FieldContent:
			values[i] = new(sql.NullString)
		case vaultitem.FieldCreatedAt, vaultitem.FieldUpdatedAt, vaultitem.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case vaultitem.ForeignKeys[0]: // tenant_vault_items
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VaultItem fields.
func (_m *VaultItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vaultitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case vaultitem.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case vaultitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case vaultitem.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case vaultitem.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = value.String
			}
		case vaultitem.FieldFileType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_type", values[i])
			} else if value.Valid {
				_m.FileType = value.String
			}
		case vaultitem.FieldEncrypted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted", values[i])
			} else if value.Valid {
				_m.Encrypted = value.Bool
			}
		case vaultitem.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case vaultitem.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case vaultitem.FieldIsDir:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_dir", values[i])
			} else if value.Valid {
				_m.IsDir = value.Bool
			}
		case vaultitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case vaultitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case vaultitem.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case vaultitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_vault_items", value)
			} else if value.Valid {
				_m.tenant_vault_items = new(int)
				*_m.tenant_vault_items = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VaultItem.
// This includes values selected through modifiers, order, etc.
func (_m *VaultItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the VaultItem entity.
func (_m *VaultItem) QueryTenant() *TenantQuery {
	return NewVaultItemClient(_m.config).QueryTenant(_m)
}

// QueryShareLinks queries the "share_links" edge of the VaultItem entity.
func (_m *VaultItem) QueryShareLinks() *VaultShareLinkQuery {
	return NewVaultItemClient(_m.config).QueryShareLinks(_m)
}

// QueryVersions queries the "versions" edge of the VaultItem entity.
func (_m *VaultItem) QueryVersions() *VaultVersionQuery {
	return NewVaultItemClient(_m.config).QueryVersions(_m)
}

// QueryComments queries the "comments" edge of the VaultItem entity.
func (_m *VaultItem) QueryComments() *VaultCommentQuery {
	return NewVaultItemClient(_m.config).QueryComments(_m)
}

// QueryFavoritedBy queries the "favorited_by" edge of the VaultItem entity.
func (_m *VaultItem) QueryFavoritedBy() *VaultFavoriteQuery {
	return NewVaultItemClient(_m.config).QueryFavoritedBy(_m)
}

// QueryLegalHolds queries the "legal_holds" edge of the VaultItem entity.
func (_m *VaultItem) QueryLegalHolds() *LegalHoldQuery {
	return NewVaultItemClient(_m.config).QueryLegalHolds(_m)
}

// Update returns a builder for updating this VaultItem.
// Note that you need to call VaultItem.Unwrap() before calling this method if this VaultItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VaultItem) Update() *VaultItemUpdateOne {
	return NewVaultItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VaultItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VaultItem) Unwrap() *VaultItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VaultItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VaultItem) String() string {
	var builder strings.Builder
	builder.WriteString("VaultItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(_m.Hash)
	builder.WriteString(", ")
	builder.WriteString("file_type=")
	builder.WriteString(_m.FileType)
	builder.WriteString(", ")
	builder.WriteString("encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Encrypted))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("is_dir=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDir))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// VaultItems is a parsable slice of VaultItem.
type VaultItems []*VaultItem
