// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/tenant"
	"sent/ent/vaultitem"
	"sent/ent/vaultsharelink"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VaultShareLinkCreate is the builder for creating a VaultShareLink entity.
type VaultShareLinkCreate struct {
	config
	mutation *VaultShareLinkMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (_c *VaultShareLinkCreate) SetToken(v string) *VaultShareLinkCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetName sets the "name" field.
func (_c *VaultShareLinkCreate) SetName(v string) *VaultShareLinkCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *VaultShareLinkCreate) SetNillableName(v *string) *VaultShareLinkCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *VaultShareLinkCreate) SetPasswordHash(v string) *VaultShareLinkCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *VaultShareLinkCreate) SetNillablePasswordHash(v *string) *VaultShareLinkCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *VaultShareLinkCreate) SetExpiresAt(v time.Time) *VaultShareLinkCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetMaxViews sets the "max_views" field.
func (_c *VaultShareLinkCreate) SetMaxViews(v int) *VaultShareLinkCreate {
	_c.mutation.SetMaxViews(v)
	return _c
}

// SetNillableMaxViews sets the "max_views" field if the given value is not nil.
func (_c *VaultShareLinkCreate) SetNillableMaxViews(v *int) *VaultShareLinkCreate {
	if v != nil {
		_c.SetMaxViews(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *VaultShareLinkCreate) SetViewCount(v int) *VaultShareLinkCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *VaultShareLinkCreate) SetNillableViewCount(v *int) *VaultShareLinkCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VaultShareLinkCreate) SetCreatedAt(v time.Time) *VaultShareLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VaultShareLinkCreate) SetNillableCreatedAt(v *time.Time) *VaultShareLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetItemID sets the "item" edge to the VaultItem entity by ID.
func (_c *VaultShareLinkCreate) SetItemID(id int) *VaultShareLinkCreate {
	_c.mutation.SetItemID(id)
	return _c
}

// SetItem sets the "item" edge to the VaultItem entity.
func (_c *VaultShareLinkCreate) SetItem(v *VaultItem) *VaultShareLinkCreate {
	return _c.SetItemID(v.ID)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *VaultShareLinkCreate) SetTenantID(id int) *VaultShareLinkCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *VaultShareLinkCreate) SetTenant(v *Tenant) *VaultShareLinkCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the VaultShareLinkMutation object of the builder.
func (_c *VaultShareLinkCreate) Mutation() *VaultShareLinkMutation {
	return _c.mutation
}

// Save creates the VaultShareLink in the database.
func (_c *VaultShareLinkCreate) Save(ctx context.Context) (*VaultShareLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VaultShareLinkCreate) SaveX(ctx context.Context) *VaultShareLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VaultShareLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VaultShareLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VaultShareLinkCreate) defaults() {
	if _, ok := _c.mutation.MaxViews(); !ok {
		v := vaultsharelink.DefaultMaxViews
		_c.mutation.SetMaxViews(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := vaultsharelink.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vaultsharelink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VaultShareLinkCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "VaultShareLink.token"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "VaultShareLink.expires_at"`)}
	}
	if _, ok := _c.mutation.MaxViews(); !ok {
		return &ValidationError{Name: "max_views", err: errors.New(`ent: missing required field "VaultShareLink.max_views"`)}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "VaultShareLink.view_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VaultShareLink.created_at"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "VaultShareLink.item"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "VaultShareLink.tenant"`)}
	}
	return nil
}

func (_c *VaultShareLinkCreate) sqlSave(ctx context.Context) (*VaultShareLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VaultShareLinkCreate) createSpec() (*VaultShareLink, *sqlgraph.CreateSpec) {
	var (
		_node = &VaultShareLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vaultsharelink.Table, sqlgraph.NewFieldSpec(vaultsharelink.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(vaultsharelink.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(vaultsharelink.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(vaultsharelink.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(vaultsharelink.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.MaxViews(); ok {
		_spec.SetField(vaultsharelink.FieldMaxViews, field.TypeInt, value)
		_node.MaxViews = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(vaultsharelink.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vaultsharelink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultsharelink.ItemTable,
			Columns: []string{vaultsharelink.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vault_item_share_links = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultsharelink.TenantTable,
			Columns: []string{vaultsharelink.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_vault_share_links = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VaultShareLinkCreateBulk is the builder for creating many VaultShareLink entities in bulk.
type VaultShareLinkCreateBulk struct {
	config
	err      error
	builders []*VaultShareLinkCreate
}

// Save creates the VaultShareLink entities in the database.
func (_c *VaultShareLinkCreateBulk) Save(ctx context.Context) ([]*VaultShareLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VaultShareLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VaultShareLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VaultShareLinkCreateBulk) SaveX(ctx context.Context) []*VaultShareLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VaultShareLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VaultShareLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
