// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/predicate"
	"sent/ent/user"
	"sent/ent/vaultcomment"
	"sent/ent/vaultitem"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VaultCommentUpdate is the builder for updating VaultComment entities.
type VaultCommentUpdate struct {
	config
	hooks     []Hook
	mutation  *VaultCommentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the VaultCommentUpdate builder.
func (_u *VaultCommentUpdate) Where(ps ...predicate.VaultComment) *VaultCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *VaultCommentUpdate) SetContent(v string) *VaultCommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *VaultCommentUpdate) SetNillableContent(v *string) *VaultCommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPage sets the "page" field.
func (_u *VaultCommentUpdate) SetPage(v int) *VaultCommentUpdate {
	_u.mutation.ResetPage()
	_u.mutation.SetPage(v)
	return _u
}

// SetNillablePage sets the "page" field if the given value is not nil.
func (_u *VaultCommentUpdate) SetNillablePage(v *int) *VaultCommentUpdate {
	if v != nil {
		_u.SetPage(*v)
	}
	return _u
}

// AddPage adds value to the "page" field.
func (_u *VaultCommentUpdate) AddPage(v int) *VaultCommentUpdate {
	_u.mutation.AddPage(v)
	return _u
}

// ClearPage clears the value of the "page" field.
func (_u *VaultCommentUpdate) ClearPage() *VaultCommentUpdate {
	_u.mutation.ClearPage()
	return _u
}

// SetX sets the "x" field.
func (_u *VaultCommentUpdate) SetX(v float64) *VaultCommentUpdate {
	_u.mutation.ResetX()
	_u.mutation.SetX(v)
	return _u
}

// SetNillableX sets the "x" field if the given value is not nil.
func (_u *VaultCommentUpdate) SetNillableX(v *float64) *VaultCommentUpdate {
	if v != nil {
		_u.SetX(*v)
	}
	return _u
}

// AddX adds value to the "x" field.
func (_u *VaultCommentUpdate) AddX(v float64) *VaultCommentUpdate {
	_u.mutation.AddX(v)
	return _u
}

// ClearX clears the value of the "x" field.
func (_u *VaultCommentUpdate) ClearX() *VaultCommentUpdate {
	_u.mutation.ClearX()
	return _u
}

// SetY sets the "y" field.
func (_u *VaultCommentUpdate) SetY(v float64) *VaultCommentUpdate {
	_u.mutation.ResetY()
	_u.mutation.SetY(v)
	return _u
}

// SetNillableY sets the "y" field if the given value is not nil.
func (_u *VaultCommentUpdate) SetNillableY(v *float64) *VaultCommentUpdate {
	if v != nil {
		_u.SetY(*v)
	}
	return _u
}

// AddY adds value to the "y" field.
func (_u *VaultCommentUpdate) AddY(v float64) *VaultCommentUpdate {
	_u.mutation.AddY(v)
	return _u
}

// ClearY clears the value of the "y" field.
func (_u *VaultCommentUpdate) ClearY() *VaultCommentUpdate {
	_u.mutation.ClearY()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VaultCommentUpdate) SetUpdatedAt(v time.Time) *VaultCommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItemID sets the "item" edge to the VaultItem entity by ID.
func (_u *VaultCommentUpdate) SetItemID(id int) *VaultCommentUpdate {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the VaultItem entity.
func (_u *VaultCommentUpdate) SetItem(v *VaultItem) *VaultCommentUpdate {
	return _u.SetItemID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *VaultCommentUpdate) SetAuthorID(id int) *VaultCommentUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *VaultCommentUpdate) SetAuthor(v *User) *VaultCommentUpdate {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the VaultCommentMutation object of the builder.
func (_u *VaultCommentUpdate) Mutation() *VaultCommentMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the VaultItem entity.
func (_u *VaultCommentUpdate) ClearItem() *VaultCommentUpdate {
	_u.mutation.ClearItem()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *VaultCommentUpdate) ClearAuthor() *VaultCommentUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VaultCommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VaultCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VaultCommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := vaultcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultCommentUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := vaultcomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "VaultComment.content": %w`, err)}
		}
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VaultComment.item"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VaultComment.author"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VaultCommentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VaultCommentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VaultCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vaultcomment.Table, vaultcomment.Columns, sqlgraph.NewFieldSpec(vaultcomment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(vaultcomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Page(); ok {
		_spec.SetField(vaultcomment.FieldPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPage(); ok {
		_spec.AddField(vaultcomment.FieldPage, field.TypeInt, value)
	}
	if _u.mutation.PageCleared() {
		_spec.ClearField(vaultcomment.FieldPage, field.TypeInt)
	}
	if value, ok := _u.mutation.X(); ok {
		_spec.SetField(vaultcomment.FieldX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedX(); ok {
		_spec.AddField(vaultcomment.FieldX, field.TypeFloat64, value)
	}
	if _u.mutation.XCleared() {
		_spec.ClearField(vaultcomment.FieldX, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Y(); ok {
		_spec.SetField(vaultcomment.FieldY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedY(); ok {
		_spec.AddField(vaultcomment.FieldY, field.TypeFloat64, value)
	}
	if _u.mutation.YCleared() {
		_spec.ClearField(vaultcomment.FieldY, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vaultcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.ItemTable,
			Columns: []string{vaultcomment.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.ItemTable,
			Columns: []string{vaultcomment.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.AuthorTable,
			Columns: []string{vaultcomment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.AuthorTable,
			Columns: []string{vaultcomment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vaultcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VaultCommentUpdateOne is the builder for updating a single VaultComment entity.
type VaultCommentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *VaultCommentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetContent sets the "content" field.
func (_u *VaultCommentUpdateOne) SetContent(v string) *VaultCommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *VaultCommentUpdateOne) SetNillableContent(v *string) *VaultCommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPage sets the "page" field.
func (_u *VaultCommentUpdateOne) SetPage(v int) *VaultCommentUpdateOne {
	_u.mutation.ResetPage()
	_u.mutation.SetPage(v)
	return _u
}

// SetNillablePage sets the "page" field if the given value is not nil.
func (_u *VaultCommentUpdateOne) SetNillablePage(v *int) *VaultCommentUpdateOne {
	if v != nil {
		_u.SetPage(*v)
	}
	return _u
}

// AddPage adds value to the "page" field.
func (_u *VaultCommentUpdateOne) AddPage(v int) *VaultCommentUpdateOne {
	_u.mutation.AddPage(v)
	return _u
}

// ClearPage clears the value of the "page" field.
func (_u *VaultCommentUpdateOne) ClearPage() *VaultCommentUpdateOne {
	_u.mutation.ClearPage()
	return _u
}

// SetX sets the "x" field.
func (_u *VaultCommentUpdateOne) SetX(v float64) *VaultCommentUpdateOne {
	_u.mutation.ResetX()
	_u.mutation.SetX(v)
	return _u
}

// SetNillableX sets the "x" field if the given value is not nil.
func (_u *VaultCommentUpdateOne) SetNillableX(v *float64) *VaultCommentUpdateOne {
	if v != nil {
		_u.SetX(*v)
	}
	return _u
}

// AddX adds value to the "x" field.
func (_u *VaultCommentUpdateOne) AddX(v float64) *VaultCommentUpdateOne {
	_u.mutation.AddX(v)
	return _u
}

// ClearX clears the value of the "x" field.
func (_u *VaultCommentUpdateOne) ClearX() *VaultCommentUpdateOne {
	_u.mutation.ClearX()
	return _u
}

// SetY sets the "y" field.
func (_u *VaultCommentUpdateOne) SetY(v float64) *VaultCommentUpdateOne {
	_u.mutation.ResetY()
	_u.mutation.SetY(v)
	return _u
}

// SetNillableY sets the "y" field if the given value is not nil.
func (_u *VaultCommentUpdateOne) SetNillableY(v *float64) *VaultCommentUpdateOne {
	if v != nil {
		_u.SetY(*v)
	}
	return _u
}

// AddY adds value to the "y" field.
func (_u *VaultCommentUpdateOne) AddY(v float64) *VaultCommentUpdateOne {
	_u.mutation.AddY(v)
	return _u
}

// ClearY clears the value of the "y" field.
func (_u *VaultCommentUpdateOne) ClearY() *VaultCommentUpdateOne {
	_u.mutation.ClearY()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VaultCommentUpdateOne) SetUpdatedAt(v time.Time) *VaultCommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItemID sets the "item" edge to the VaultItem entity by ID.
func (_u *VaultCommentUpdateOne) SetItemID(id int) *VaultCommentUpdateOne {
	_u.mutation.SetItemID(id)
	return _u
}

// SetItem sets the "item" edge to the VaultItem entity.
func (_u *VaultCommentUpdateOne) SetItem(v *VaultItem) *VaultCommentUpdateOne {
	return _u.SetItemID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *VaultCommentUpdateOne) SetAuthorID(id int) *VaultCommentUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *VaultCommentUpdateOne) SetAuthor(v *User) *VaultCommentUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the VaultCommentMutation object of the builder.
func (_u *VaultCommentUpdateOne) Mutation() *VaultCommentMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the VaultItem entity.
func (_u *VaultCommentUpdateOne) ClearItem() *VaultCommentUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *VaultCommentUpdateOne) ClearAuthor() *VaultCommentUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// Where appends a list predicates to the VaultCommentUpdate builder.
func (_u *VaultCommentUpdateOne) Where(ps ...predicate.VaultComment) *VaultCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VaultCommentUpdateOne) Select(field string, fields ...string) *VaultCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VaultComment entity.
func (_u *VaultCommentUpdateOne) Save(ctx context.Context) (*VaultComment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultCommentUpdateOne) SaveX(ctx context.Context) *VaultComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VaultCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VaultCommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := vaultcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultCommentUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := vaultcomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "VaultComment.content": %w`, err)}
		}
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VaultComment.item"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VaultComment.author"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VaultCommentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VaultCommentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VaultCommentUpdateOne) sqlSave(ctx context.Context) (_node *VaultComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vaultcomment.Table, vaultcomment.Columns, sqlgraph.NewFieldSpec(vaultcomment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VaultComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vaultcomment.FieldID)
		for _, f := range fields {
			if !vaultcomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vaultcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(vaultcomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Page(); ok {
		_spec.SetField(vaultcomment.FieldPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPage(); ok {
		_spec.AddField(vaultcomment.FieldPage, field.TypeInt, value)
	}
	if _u.mutation.PageCleared() {
		_spec.ClearField(vaultcomment.FieldPage, field.TypeInt)
	}
	if value, ok := _u.mutation.X(); ok {
		_spec.SetField(vaultcomment.FieldX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedX(); ok {
		_spec.AddField(vaultcomment.FieldX, field.TypeFloat64, value)
	}
	if _u.mutation.XCleared() {
		_spec.ClearField(vaultcomment.FieldX, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Y(); ok {
		_spec.SetField(vaultcomment.FieldY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedY(); ok {
		_spec.AddField(vaultcomment.FieldY, field.TypeFloat64, value)
	}
	if _u.mutation.YCleared() {
		_spec.ClearField(vaultcomment.FieldY, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vaultcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.ItemTable,
			Columns: []string{vaultcomment.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.ItemTable,
			Columns: []string{vaultcomment.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.AuthorTable,
			Columns: []string{vaultcomment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultcomment.AuthorTable,
			Columns: []string{vaultcomment.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &VaultComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vaultcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
