// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sent/ent/predicate"
	"sent/ent/tenant"
	"sent/ent/vaultitem"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VaultItemUpdate is the builder for updating VaultItem entities.
type VaultItemUpdate struct {
	config
	hooks    []Hook
	mutation *VaultItemMutation
}

// Where appends a list predicates to the VaultItemUpdate builder.
func (_u *VaultItemUpdate) Where(ps ...predicate.VaultItem) *VaultItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPath sets the "path" field.
func (_u *VaultItemUpdate) SetPath(v string) *VaultItemUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *VaultItemUpdate) SetNillablePath(v *string) *VaultItemUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *VaultItemUpdate) SetName(v string) *VaultItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VaultItemUpdate) SetNillableName(v *string) *VaultItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *VaultItemUpdate) SetSize(v int64) *VaultItemUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *VaultItemUpdate) SetNillableSize(v *int64) *VaultItemUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *VaultItemUpdate) AddSize(v int64) *VaultItemUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *VaultItemUpdate) SetHash(v string) *VaultItemUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *VaultItemUpdate) SetNillableHash(v *string) *VaultItemUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *VaultItemUpdate) SetContent(v string) *VaultItemUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *VaultItemUpdate) SetNillableContent(v *string) *VaultItemUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *VaultItemUpdate) ClearContent() *VaultItemUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetIsDir sets the "is_dir" field.
func (_u *VaultItemUpdate) SetIsDir(v bool) *VaultItemUpdate {
	_u.mutation.SetIsDir(v)
	return _u
}

// SetNillableIsDir sets the "is_dir" field if the given value is not nil.
func (_u *VaultItemUpdate) SetNillableIsDir(v *bool) *VaultItemUpdate {
	if v != nil {
		_u.SetIsDir(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VaultItemUpdate) SetUpdatedAt(v time.Time) *VaultItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *VaultItemUpdate) SetTenantID(id int) *VaultItemUpdate {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *VaultItemUpdate) SetTenant(v *Tenant) *VaultItemUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the VaultItemMutation object of the builder.
func (_u *VaultItemUpdate) Mutation() *VaultItemMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *VaultItemUpdate) ClearTenant() *VaultItemUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VaultItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VaultItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VaultItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := vaultitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultItemUpdate) check() error {
	if v, ok := _u.mutation.Path(); ok {
		if err := vaultitem.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "VaultItem.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := vaultitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VaultItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := vaultitem.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "VaultItem.hash": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VaultItem.tenant"`)
	}
	return nil
}

func (_u *VaultItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vaultitem.Table, vaultitem.Columns, sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(vaultitem.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vaultitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(vaultitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(vaultitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(vaultitem.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(vaultitem.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(vaultitem.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.IsDir(); ok {
		_spec.SetField(vaultitem.FieldIsDir, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vaultitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultitem.TenantTable,
			Columns: []string{vaultitem.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultitem.TenantTable,
			Columns: []string{vaultitem.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vaultitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VaultItemUpdateOne is the builder for updating a single VaultItem entity.
type VaultItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VaultItemMutation
}

// SetPath sets the "path" field.
func (_u *VaultItemUpdateOne) SetPath(v string) *VaultItemUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *VaultItemUpdateOne) SetNillablePath(v *string) *VaultItemUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *VaultItemUpdateOne) SetName(v string) *VaultItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VaultItemUpdateOne) SetNillableName(v *string) *VaultItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *VaultItemUpdateOne) SetSize(v int64) *VaultItemUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *VaultItemUpdateOne) SetNillableSize(v *int64) *VaultItemUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *VaultItemUpdateOne) AddSize(v int64) *VaultItemUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *VaultItemUpdateOne) SetHash(v string) *VaultItemUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *VaultItemUpdateOne) SetNillableHash(v *string) *VaultItemUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *VaultItemUpdateOne) SetContent(v string) *VaultItemUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *VaultItemUpdateOne) SetNillableContent(v *string) *VaultItemUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *VaultItemUpdateOne) ClearContent() *VaultItemUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetIsDir sets the "is_dir" field.
func (_u *VaultItemUpdateOne) SetIsDir(v bool) *VaultItemUpdateOne {
	_u.mutation.SetIsDir(v)
	return _u
}

// SetNillableIsDir sets the "is_dir" field if the given value is not nil.
func (_u *VaultItemUpdateOne) SetNillableIsDir(v *bool) *VaultItemUpdateOne {
	if v != nil {
		_u.SetIsDir(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VaultItemUpdateOne) SetUpdatedAt(v time.Time) *VaultItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_u *VaultItemUpdateOne) SetTenantID(id int) *VaultItemUpdateOne {
	_u.mutation.SetTenantID(id)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *VaultItemUpdateOne) SetTenant(v *Tenant) *VaultItemUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the VaultItemMutation object of the builder.
func (_u *VaultItemUpdateOne) Mutation() *VaultItemMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *VaultItemUpdateOne) ClearTenant() *VaultItemUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the VaultItemUpdate builder.
func (_u *VaultItemUpdateOne) Where(ps ...predicate.VaultItem) *VaultItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VaultItemUpdateOne) Select(field string, fields ...string) *VaultItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VaultItem entity.
func (_u *VaultItemUpdateOne) Save(ctx context.Context) (*VaultItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultItemUpdateOne) SaveX(ctx context.Context) *VaultItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VaultItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VaultItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := vaultitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultItemUpdateOne) check() error {
	if v, ok := _u.mutation.Path(); ok {
		if err := vaultitem.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "VaultItem.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := vaultitem.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VaultItem.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := vaultitem.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "VaultItem.hash": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VaultItem.tenant"`)
	}
	return nil
}

func (_u *VaultItemUpdateOne) sqlSave(ctx context.Context) (_node *VaultItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vaultitem.Table, vaultitem.Columns, sqlgraph.NewFieldSpec(vaultitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VaultItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vaultitem.FieldID)
		for _, f := range fields {
			if !vaultitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vaultitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(vaultitem.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vaultitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(vaultitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(vaultitem.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(vaultitem.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(vaultitem.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(vaultitem.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.IsDir(); ok {
		_spec.SetField(vaultitem.FieldIsDir, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vaultitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultitem.TenantTable,
			Columns: []string{vaultitem.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vaultitem.TenantTable,
			Columns: []string{vaultitem.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VaultItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vaultitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
