// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_job_posting.sql

package peopledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobPosting = `-- name: CreateJobPosting :one
INSERT INTO
    job_postings (
        tenant_id,
        title,
        description,
        status
    )
VALUES ($1, $2, $3, 'draft')
RETURNING
    id
`

type CreateJobPostingParams struct {
	TenantID    int32       `json:"tenant_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateJobPosting(ctx context.Context, arg CreateJobPostingParams) (int32, error) {
	row := q.db.QueryRow(ctx, createJobPosting, arg.TenantID, arg.Title, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}
