// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_products.sql

package stockdb

import (
	"context"
)

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, sku, name, description, unit_cost, quantity, created_at, updated_at FROM products WHERE tenant_id = $1 ORDER BY name ASC
`

func (q *Queries) ListProducts(ctx context.Context, tenantID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.UnitCost,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
