// Code generated by ent, DO NOT EDIT.

package saasfilter

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the saasfilter type in the database.
	Label = "saa_sfilter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomainPattern holds the string denoting the domain_pattern field in the database.
	FieldDomainPattern = "domain_pattern"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldIsSniBased holds the string denoting the is_sni_based field in the database.
	FieldIsSniBased = "is_sni_based"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeApp holds the string denoting the app edge name in mutations.
	EdgeApp = "app"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the saasfilter in the database.
	Table = "saa_sfilters"
	// AppTable is the table that holds the app relation/edge.
	AppTable = "saa_sfilters"
	// AppInverseTable is the table name for the SaaSApp entity.
	// It exists in this package in order to avoid circular dependency with the "saasapp" package.
	AppInverseTable = "saa_sapps"
	// AppColumn is the table column denoting the app relation/edge.
	AppColumn = "saa_sapp_filters"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "saa_sfilters"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_saas_filters"
)

// Columns holds all SQL columns for saasfilter fields.
var Columns = []string{
	FieldID,
	FieldDomainPattern,
	FieldAction,
	FieldReason,
	FieldIsSniBased,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "saa_sfilters"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"saa_sapp_filters",
	"tenant_saas_filters",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DomainPatternValidator is a validator for the "domain_pattern" field. It is called by the builders before save.
	DomainPatternValidator func(string) error
	// DefaultIsSniBased holds the default value on creation for the "is_sni_based" field.
	DefaultIsSniBased bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Action defines the type for the "action" enum field.
type Action string

// ActionBLOCK is the default value of the Action enum.
const DefaultAction = ActionBLOCK

// Action values.
const (
	ActionALLOW Action = "ALLOW"
	ActionBLOCK Action = "BLOCK"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionALLOW, ActionBLOCK:
		return nil
	default:
		return fmt.Errorf("saasfilter: invalid enum value for action field: %q", a)
	}
}

// OrderOption defines the ordering options for the SaaSFilter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomainPattern orders the results by the domain_pattern field.
func ByDomainPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainPattern, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByIsSniBased orders the results by the is_sni_based field.
func ByIsSniBased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSniBased, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAppField orders the results by app field.
func ByAppField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAppStep(), sql.OrderByField(field, opts...))
	}
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}
func newAppStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AppInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
	)
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
