// Code generated by ent, DO NOT EDIT.

package healthscoresnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the healthscoresnapshot type in the database.
	Label = "health_score_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOverallScore holds the string denoting the overall_score field in the database.
	FieldOverallScore = "overall_score"
	// FieldPerformanceScore holds the string denoting the performance_score field in the database.
	FieldPerformanceScore = "performance_score"
	// FieldSecurityScore holds the string denoting the security_score field in the database.
	FieldSecurityScore = "security_score"
	// FieldLifecycleScore holds the string denoting the lifecycle_score field in the database.
	FieldLifecycleScore = "lifecycle_score"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the healthscoresnapshot in the database.
	Table = "health_score_snapshots"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "health_score_snapshots"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_health_snapshots"
)

// Columns holds all SQL columns for healthscoresnapshot fields.
var Columns = []string{
	FieldID,
	FieldOverallScore,
	FieldPerformanceScore,
	FieldSecurityScore,
	FieldLifecycleScore,
	FieldMetadata,
	FieldTimestamp,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "health_score_snapshots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"tenant_health_snapshots",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
)

// OrderOption defines the ordering options for the HealthScoreSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOverallScore orders the results by the overall_score field.
func ByOverallScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverallScore, opts...).ToFunc()
}

// ByPerformanceScore orders the results by the performance_score field.
func ByPerformanceScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformanceScore, opts...).ToFunc()
}

// BySecurityScore orders the results by the security_score field.
func BySecurityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecurityScore, opts...).ToFunc()
}

// ByLifecycleScore orders the results by the lifecycle_score field.
func ByLifecycleScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifecycleScore, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
