// Code generated by ent, DO NOT EDIT.

package user

import (
	"sent/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// ZitadelID applies equality check predicate on the "zitadel_id" field. It's identical to ZitadelIDEQ.
func ZitadelID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldZitadelID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// FirstName applies equality check predicate on the "first_name" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstName, v))
}

// LastName applies equality check predicate on the "last_name" field. It's identical to LastNameEQ.
func LastName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastName, v))
}

// JobTitle applies equality check predicate on the "job_title" field. It's identical to JobTitleEQ.
func JobTitle(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldJobTitle, v))
}

// Department applies equality check predicate on the "department" field. It's identical to DepartmentEQ.
func Department(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDepartment, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// MaxWip applies equality check predicate on the "max_wip" field. It's identical to MaxWipEQ.
func MaxWip(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMaxWip, v))
}

// ZitadelIDEQ applies the EQ predicate on the "zitadel_id" field.
func ZitadelIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldZitadelID, v))
}

// ZitadelIDNEQ applies the NEQ predicate on the "zitadel_id" field.
func ZitadelIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldZitadelID, v))
}

// ZitadelIDIn applies the In predicate on the "zitadel_id" field.
func ZitadelIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldZitadelID, vs...))
}

// ZitadelIDNotIn applies the NotIn predicate on the "zitadel_id" field.
func ZitadelIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldZitadelID, vs...))
}

// ZitadelIDGT applies the GT predicate on the "zitadel_id" field.
func ZitadelIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldZitadelID, v))
}

// ZitadelIDGTE applies the GTE predicate on the "zitadel_id" field.
func ZitadelIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldZitadelID, v))
}

// ZitadelIDLT applies the LT predicate on the "zitadel_id" field.
func ZitadelIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldZitadelID, v))
}

// ZitadelIDLTE applies the LTE predicate on the "zitadel_id" field.
func ZitadelIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldZitadelID, v))
}

// ZitadelIDContains applies the Contains predicate on the "zitadel_id" field.
func ZitadelIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldZitadelID, v))
}

// ZitadelIDHasPrefix applies the HasPrefix predicate on the "zitadel_id" field.
func ZitadelIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldZitadelID, v))
}

// ZitadelIDHasSuffix applies the HasSuffix predicate on the "zitadel_id" field.
func ZitadelIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldZitadelID, v))
}

// ZitadelIDEqualFold applies the EqualFold predicate on the "zitadel_id" field.
func ZitadelIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldZitadelID, v))
}

// ZitadelIDContainsFold applies the ContainsFold predicate on the "zitadel_id" field.
func ZitadelIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldZitadelID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// FirstNameEQ applies the EQ predicate on the "first_name" field.
func FirstNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "first_name" field.
func FirstNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "first_name" field.
func FirstNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "first_name" field.
func FirstNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "first_name" field.
func FirstNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "first_name" field.
func FirstNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "first_name" field.
func FirstNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "first_name" field.
func FirstNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "first_name" field.
func FirstNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "first_name" field.
func FirstNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "first_name" field.
func FirstNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameIsNil applies the IsNil predicate on the "first_name" field.
func FirstNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldFirstName))
}

// FirstNameNotNil applies the NotNil predicate on the "first_name" field.
func FirstNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldFirstName))
}

// FirstNameEqualFold applies the EqualFold predicate on the "first_name" field.
func FirstNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "first_name" field.
func FirstNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldFirstName, v))
}

// LastNameEQ applies the EQ predicate on the "last_name" field.
func LastNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastName, v))
}

// LastNameNEQ applies the NEQ predicate on the "last_name" field.
func LastNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastName, v))
}

// LastNameIn applies the In predicate on the "last_name" field.
func LastNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastName, vs...))
}

// LastNameNotIn applies the NotIn predicate on the "last_name" field.
func LastNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastName, vs...))
}

// LastNameGT applies the GT predicate on the "last_name" field.
func LastNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastName, v))
}

// LastNameGTE applies the GTE predicate on the "last_name" field.
func LastNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastName, v))
}

// LastNameLT applies the LT predicate on the "last_name" field.
func LastNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastName, v))
}

// LastNameLTE applies the LTE predicate on the "last_name" field.
func LastNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastName, v))
}

// LastNameContains applies the Contains predicate on the "last_name" field.
func LastNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLastName, v))
}

// LastNameHasPrefix applies the HasPrefix predicate on the "last_name" field.
func LastNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLastName, v))
}

// LastNameHasSuffix applies the HasSuffix predicate on the "last_name" field.
func LastNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLastName, v))
}

// LastNameIsNil applies the IsNil predicate on the "last_name" field.
func LastNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLastName))
}

// LastNameNotNil applies the NotNil predicate on the "last_name" field.
func LastNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLastName))
}

// LastNameEqualFold applies the EqualFold predicate on the "last_name" field.
func LastNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLastName, v))
}

// LastNameContainsFold applies the ContainsFold predicate on the "last_name" field.
func LastNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLastName, v))
}

// JobTitleEQ applies the EQ predicate on the "job_title" field.
func JobTitleEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldJobTitle, v))
}

// JobTitleNEQ applies the NEQ predicate on the "job_title" field.
func JobTitleNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldJobTitle, v))
}

// JobTitleIn applies the In predicate on the "job_title" field.
func JobTitleIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldJobTitle, vs...))
}

// JobTitleNotIn applies the NotIn predicate on the "job_title" field.
func JobTitleNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldJobTitle, vs...))
}

// JobTitleGT applies the GT predicate on the "job_title" field.
func JobTitleGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldJobTitle, v))
}

// JobTitleGTE applies the GTE predicate on the "job_title" field.
func JobTitleGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldJobTitle, v))
}

// JobTitleLT applies the LT predicate on the "job_title" field.
func JobTitleLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldJobTitle, v))
}

// JobTitleLTE applies the LTE predicate on the "job_title" field.
func JobTitleLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldJobTitle, v))
}

// JobTitleContains applies the Contains predicate on the "job_title" field.
func JobTitleContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldJobTitle, v))
}

// JobTitleHasPrefix applies the HasPrefix predicate on the "job_title" field.
func JobTitleHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldJobTitle, v))
}

// JobTitleHasSuffix applies the HasSuffix predicate on the "job_title" field.
func JobTitleHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldJobTitle, v))
}

// JobTitleIsNil applies the IsNil predicate on the "job_title" field.
func JobTitleIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldJobTitle))
}

// JobTitleNotNil applies the NotNil predicate on the "job_title" field.
func JobTitleNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldJobTitle))
}

// JobTitleEqualFold applies the EqualFold predicate on the "job_title" field.
func JobTitleEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldJobTitle, v))
}

// JobTitleContainsFold applies the ContainsFold predicate on the "job_title" field.
func JobTitleContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldJobTitle, v))
}

// DepartmentEQ applies the EQ predicate on the "department" field.
func DepartmentEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDepartment, v))
}

// DepartmentNEQ applies the NEQ predicate on the "department" field.
func DepartmentNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDepartment, v))
}

// DepartmentIn applies the In predicate on the "department" field.
func DepartmentIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDepartment, vs...))
}

// DepartmentNotIn applies the NotIn predicate on the "department" field.
func DepartmentNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDepartment, vs...))
}

// DepartmentGT applies the GT predicate on the "department" field.
func DepartmentGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDepartment, v))
}

// DepartmentGTE applies the GTE predicate on the "department" field.
func DepartmentGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDepartment, v))
}

// DepartmentLT applies the LT predicate on the "department" field.
func DepartmentLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDepartment, v))
}

// DepartmentLTE applies the LTE predicate on the "department" field.
func DepartmentLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDepartment, v))
}

// DepartmentContains applies the Contains predicate on the "department" field.
func DepartmentContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDepartment, v))
}

// DepartmentHasPrefix applies the HasPrefix predicate on the "department" field.
func DepartmentHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDepartment, v))
}

// DepartmentHasSuffix applies the HasSuffix predicate on the "department" field.
func DepartmentHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDepartment, v))
}

// DepartmentIsNil applies the IsNil predicate on the "department" field.
func DepartmentIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldDepartment))
}

// DepartmentNotNil applies the NotNil predicate on the "department" field.
func DepartmentNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldDepartment))
}

// DepartmentEqualFold applies the EqualFold predicate on the "department" field.
func DepartmentEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDepartment, v))
}

// DepartmentContainsFold applies the ContainsFold predicate on the "department" field.
func DepartmentContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDepartment, v))
}

// ExternalMappingsIsNil applies the IsNil predicate on the "external_mappings" field.
func ExternalMappingsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldExternalMappings))
}

// ExternalMappingsNotNil applies the NotNil predicate on the "external_mappings" field.
func ExternalMappingsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldExternalMappings))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldRole, v))
}

// SeniorityEQ applies the EQ predicate on the "seniority" field.
func SeniorityEQ(v Seniority) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSeniority, v))
}

// SeniorityNEQ applies the NEQ predicate on the "seniority" field.
func SeniorityNEQ(v Seniority) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSeniority, v))
}

// SeniorityIn applies the In predicate on the "seniority" field.
func SeniorityIn(vs ...Seniority) predicate.User {
	return predicate.User(sql.FieldIn(FieldSeniority, vs...))
}

// SeniorityNotIn applies the NotIn predicate on the "seniority" field.
func SeniorityNotIn(vs ...Seniority) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSeniority, vs...))
}

// MaxWipEQ applies the EQ predicate on the "max_wip" field.
func MaxWipEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMaxWip, v))
}

// MaxWipNEQ applies the NEQ predicate on the "max_wip" field.
func MaxWipNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMaxWip, v))
}

// MaxWipIn applies the In predicate on the "max_wip" field.
func MaxWipIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldMaxWip, vs...))
}

// MaxWipNotIn applies the NotIn predicate on the "max_wip" field.
func MaxWipNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMaxWip, vs...))
}

// MaxWipGT applies the GT predicate on the "max_wip" field.
func MaxWipGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldMaxWip, v))
}

// MaxWipGTE applies the GTE predicate on the "max_wip" field.
func MaxWipGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMaxWip, v))
}

// MaxWipLT applies the LT predicate on the "max_wip" field.
func MaxWipLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldMaxWip, v))
}

// MaxWipLTE applies the LTE predicate on the "max_wip" field.
func MaxWipLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMaxWip, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPermissions applies the HasEdge predicate on the "permissions" edge.
func HasPermissions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, PermissionsTable, PermissionsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPermissionsWith applies the HasEdge predicate on the "permissions" edge with a given conditions (other predicates).
func HasPermissionsWith(preds ...predicate.Permission) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPermissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequestedTickets applies the HasEdge predicate on the "requested_tickets" edge.
func HasRequestedTickets() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RequestedTicketsTable, RequestedTicketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestedTicketsWith applies the HasEdge predicate on the "requested_tickets" edge with a given conditions (other predicates).
func HasRequestedTicketsWith(preds ...predicate.Ticket) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRequestedTicketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedTickets applies the HasEdge predicate on the "assigned_tickets" edge.
func HasAssignedTickets() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignedTicketsTable, AssignedTicketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedTicketsWith applies the HasEdge predicate on the "assigned_tickets" edge with a given conditions (other predicates).
func HasAssignedTicketsWith(preds ...predicate.Ticket) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAssignedTicketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTimeEntries applies the HasEdge predicate on the "time_entries" edge.
func HasTimeEntries() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TimeEntriesTable, TimeEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTimeEntriesWith applies the HasEdge predicate on the "time_entries" edge with a given conditions (other predicates).
func HasTimeEntriesWith(preds ...predicate.TimeEntry) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newTimeEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnedAssets applies the HasEdge predicate on the "owned_assets" edge.
func HasOwnedAssets() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OwnedAssetsTable, OwnedAssetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnedAssetsWith applies the HasEdge predicate on the "owned_assets" edge with a given conditions (other predicates).
func HasOwnedAssetsWith(preds ...predicate.Asset) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newOwnedAssetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthoredSops applies the HasEdge predicate on the "authored_sops" edge.
func HasAuthoredSops() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuthoredSopsTable, AuthoredSopsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthoredSopsWith applies the HasEdge predicate on the "authored_sops" edge with a given conditions (other predicates).
func HasAuthoredSopsWith(preds ...predicate.SOP) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAuthoredSopsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCallLogs applies the HasEdge predicate on the "call_logs" edge.
func HasCallLogs() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CallLogsTable, CallLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCallLogsWith applies the HasEdge predicate on the "call_logs" edge with a given conditions (other predicates).
func HasCallLogsWith(preds ...predicate.CallLog) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCallLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVoicemails applies the HasEdge predicate on the "voicemails" edge.
func HasVoicemails() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VoicemailsTable, VoicemailsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVoicemailsWith applies the HasEdge predicate on the "voicemails" edge with a given conditions (other predicates).
func HasVoicemailsWith(preds ...predicate.Voicemail) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newVoicemailsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSaasIdentities applies the HasEdge predicate on the "saas_identities" edge.
func HasSaasIdentities() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SaasIdentitiesTable, SaasIdentitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSaasIdentitiesWith applies the HasEdge predicate on the "saas_identities" edge with a given conditions (other predicates).
func HasSaasIdentitiesWith(preds ...predicate.SaaSIdentity) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSaasIdentitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
